implement popular articles (http)
Ptt-official-app/Ptt-backend pull request #113
Opened 2021-03-02 12:29 UTC by linmeichu

## 👏 解決掉的 issue / Resolved Issues
- https://github.com/Ptt-official-app/Ptt-backend/issues/107

## 📝 相關的 issue / Related Issues
- https://github.com/Ptt-official-app/Ptt-backend/issues/83
- https://github.com/Ptt-official-app/Ptt-backend/issues/86

## ⛏ 變更內容 / Details of Changes
- 實作熱門文章的 http 套件

2021-03-02 12:33 UTC, PichuChen approved these changes
LGTM

2021-03-02 12:34 UTC, PichuChen commented
可以再到 Slack 上面邀請其他人幫忙 Review 喔

2021-03-02 13:30 UTC, gn01842919 commented
可以補上簡單的測試嗎？

2021-03-02 13:33 UTC, gn01842919 requested changes
可以補上簡單的測試嗎？

2021-03-02 13:43 UTC, gn01842919 commented on internal/delivery/http/route_popular_articles.go
> +}
檔案最後面依照其他檔案留一個空行應該比較好

2021-03-02 13:57 UTC, linmeichu commented on internal/delivery/http/route_popular_articles.go
> +}
@gn01842919 
是因為會編譯上可能會發生問題嗎？
https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2021-03-02 14:00 UTC, gn01842919 commented on internal/delivery/http/route_popular_articles.go
> +}
其實我也沒有覺得非要不可，只是覺得維持一致比較好，所以這邊是用單純的留言而沒有 request change

2021-03-02 14:35 UTC, PichuChen approved these changes
LGTM

2021-03-02 15:36 UTC, gn01842919 approved these changes
LGTM

2021-03-03 11:25 UTC, gn01842919 approved these changes

2021-03-03 11:31 UTC, gn01842919 approved these changes

2021-03-03 11:32 UTC, merged