實作個人看板歷史文章
Ptt-official-app/Ptt-backend pull request #123
Opened 2021-03-08 05:13 UTC by whitefloor

## 👏 解決掉的 issue / Resolved Issues
- close #59 

## 📝 相關的 issue / Related Issues
- #59 

## ⛏ 變更內容 / Details of Changes

- 實作 http/usecase/repository
- 測試 http/usecase

2021-03-08 06:09 UTC, whitefloor commented
= = 我少寫了mock的method 晚點補上

2021-03-10 08:37 UTC, Julian-Chu requested changes
我查API文件沒看到這個feature，在文件的哪一段?

2021-03-10 08:37 UTC, Julian-Chu commented on internal/delivery/http/route_users.go
> +	token := delivery.getTokenFromRequest(r)
處理沒有 token的情況  403

2021-03-10 08:37 UTC, Julian-Chu commented on internal/delivery/http/route_users.go
> +	}
錯誤處理不打算回傳400或500嗎

2021-03-10 08:37 UTC, Julian-Chu commented on internal/repository/user.go
> +func (repo *repository) GetUserArticles(_ context.Context, boardID string) ([]bbs.ArticleRecord, error) {
GetUserArticles  沒有傳入userID 有點奇怪， 在確認一下命名或business logic

2021-03-10 12:21 UTC, PichuChen commented
這個是同時實作 http/usecase/delivery 這樣嗎？

2021-03-10 13:08 UTC, whitefloor commented on internal/repository/user.go
> +func (repo *repository) GetUserArticles(_ context.Context, boardID string) ([]bbs.ArticleRecord, error) {
這個有討論過，因為沒有存user有哪些歷史文章
所以需要先取得所有公開看板ID
再從這些看板裡面找到屬於user的文章

2021-03-10 13:09 UTC, whitefloor commented on internal/repository/user.go
> +func (repo *repository) GetUserArticles(_ context.Context, boardID string) ([]bbs.ArticleRecord, error) {
我在裡面加個註解好了，以免遺忘

2021-03-10 13:11 UTC, whitefloor commented
> 這個是同時實作 http/usecase/delivery 這樣嗎？

對的，我改一下說明寫得清楚一點

2021-03-10 13:18 UTC, whitefloor commented on internal/delivery/http/route_users.go
> +	token := delivery.getTokenFromRequest(r)
這段在測試的時候有做到
目前是在head沒有拿到id的時候會會有log顯示有問題
但目前沒有處理機制

2021-03-10 13:23 UTC, whitefloor commented on internal/delivery/http/route_users.go
> +	}
這個我補一下，感謝
有錯回傳StatusBadRequest

2021-03-10 13:30 UTC, whitefloor commented
> 我查API文件沒看到這個feature，在文件的哪一段?

搜尋 /v1/users/{{user_id}}/articles

2021-03-10 13:34 UTC, Julian-Chu commented on internal/repository/user.go
> +func (repo *repository) GetUserArticles(_ context.Context, boardID string) ([]bbs.ArticleRecord, error) {
那可能要思考一下這個 method是不是需要的,  目前的method只是把GetBoardArticleRecords 換個名字而已有點重複的味道 ,  我會考慮兩種做法
- 現有的 board repo interface 在usecase 作aggregation就好,  移除掉這個method
- 或是把 aggregation都移到這來, 讓usecase 單純

2021-03-10 13:35 UTC, Julian-Chu commented on internal/usecase/user.go
> +	for _, v := range boards {
這邊的變數名 b或board都會比v好

2021-03-10 18:40 UTC, whitefloor commented on internal/usecase/user.go
> +	for _, v := range boards {
好的，這個我改一下

2021-03-10 18:55 UTC, whitefloor commented on internal/repository/user.go
> +func (repo *repository) GetUserArticles(_ context.Context, boardID string) ([]bbs.ArticleRecord, error) {
因為目前是資料儲存的方法剛好要使用同樣的方法找資料，才會與GetBoardArticleRecords封裝了同樣的query
從架構上來看GetUserArticles也有delivery/usecase/reposiroty三個完整的區分，可讀性也會較高
日後如果需要做出區分GetBoardArticleRecords & GetUserArticles repository的邏輯的時候也能減少耦合問題
這我不太贊成使用同一個repository method對應到兩個不同邏輯的usecase

2021-03-11 02:48 UTC, xboxa5105 approved these changes

2021-03-14 17:09 UTC, Julian-Chu approved these changes
LGTM

2021-03-14 17:15 UTC, merged