Implement get board information for usecase and delivery/http
Ptt-official-app/Ptt-backend pull request #127
Opened 2021-03-10 05:51 UTC by gogog22510

## 👏 解決掉的 issue / Resolved Issues
- close #126

## 📝 相關的 issue / Related Issues
- #63

## ⛏ 變更內容 / Details of Changes
- 實作 http/usecase
- 測試 http/usecase

2021-03-10 08:06 UTC, wagaru commented on internal/usecase/board.go
> +		return nil, fmt.Errorf("get board %s posts limit error: %w", boardID, err)
typo？

2021-03-11 05:44 UTC, wagaru commented
LGTM

2021-03-11 07:26 UTC, Julian-Chu requested changes
typo : limition should be limitation or limit

2021-03-11 20:04 UTC, gogog22510 commented
我是參考[API 文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)上面的field.... 上面是寫post_limition, 我在文件上面建議改成post_limitation了，假如接受的話我可以一併改動

2021-03-12 03:08 UTC, PichuChen commented
> 我是參考[API 文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#)上面的field.... 上面是寫post_limition, 我在文件上面建議改成post_limitation了，假如接受的話我可以一併改動

https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit?ts=6016b0fb#

筆誤的部分修正了，目前最新版本是 Draft 15

2021-03-13 07:16 UTC, wagaru approved these changes

2021-03-13 08:19 UTC, Julian-Chu approved these changes

2021-03-13 10:22 UTC, merged