Feature/#148 #user preferences usecase and repository
Ptt-official-app/Ptt-backend pull request #150
Opened 2021-03-29 20:32 UTC by kyho4515

## 👏 解決掉的 issue / Resolved Issues
- close #148 

## 📝 相關的 issue / Related Issues
- #62 

## ⛏ 變更內容 / Details of Changes
- 在repository新增mock的GetUserPreferences: 修改的檔案有internal/repository/repository.go 及internal/repository/user.go
- 修改internal/usecase/user.go內的GetUserPreferences: 直接呼叫repository的GetUserPreferences
- 在internal/usecase/user_mock_test.go為MockRepository新增GetUserPreferences

2021-03-30 08:36 UTC, y2468101216 commented
LGTM

2021-03-30 09:54 UTC, PichuChen requested changes

2021-03-30 09:54 UTC, PichuChen commented on internal/repository/user.go
> +// TODO: mock method for usecase.GetUserPreferences, replace it with real bbs record
這個應該是 for repository ?

2021-03-30 09:54 UTC, PichuChen commented on internal/usecase/user.go
> +	preferencesRec, err := usecase.repo.GetUserPreferences(ctx, userID)
rec 就行了

2021-03-30 09:54 UTC, PichuChen commented on internal/usecase/user_mock_test.go
> +	return map[string]string{"favorite_no_highlight": "YES"}, nil
他回應應該不是 "YES" ?

2021-03-30 18:17 UTC, kyho4515 commented on internal/repository/user.go
> +// TODO: mock method for usecase.GetUserPreferences, replace it with real bbs record
原本是想說為usecase建的mock method. 我把它改得明確一點

2021-03-30 18:17 UTC, kyho4515 commented on internal/usecase/user.go
> +	preferencesRec, err := usecase.repo.GetUserPreferences(ctx, userID)
OK

2021-03-30 18:18 UTC, kyho4515 commented on internal/usecase/user_mock_test.go
> +	return map[string]string{"favorite_no_highlight": "YES"}, nil
OK

2021-04-02 07:49 UTC, PichuChen approved these changes
LGTM

2021-04-02 07:49 UTC, merged