Implement http for user information and enhance test case
Ptt-official-app/Ptt-backend pull request #159
Opened 2021-04-02 04:22 UTC by gogog22510

## 👏 解決掉的 issue / Resolved Issues
- close #100 

## 📝 相關的 issue / Related Issues
- #主 issue #52 

## ⛏ 變更內容 / Details of Changes
- 修改error message
- 檢查token permission for real name and money
- 補齊testcode

2021-04-02 07:42 UTC, PichuChen commented on internal/delivery/http/route_users_test.go
> +func checkUserField(t *testing.T, data map[string]interface{}, field string, expected interface{}) {
這邊有辦法不用另外定義函式嗎？

2021-04-02 07:46 UTC, PichuChen commented on internal/usecase/token.go
> +	PermissionReadUserRealName        Permission = "READ_USER_REAL_NAME"
在需求上應該是沒有這樣的設計？

2021-04-02 07:47 UTC, PichuChen requested changes
請先按照 ISSUE 上面的實作，如果有其他要修改的請另外開 ISSUE 討論。

2021-04-03 15:56 UTC, gogog22510 commented on internal/usecase/token.go
> +	PermissionReadUserRealName        Permission = "READ_USER_REAL_NAME"
在/v1/users/{{user_id}}/information裡有提到需要檢查permission。不需要的話我可以拿掉

2021-04-03 15:57 UTC, gogog22510 commented on internal/delivery/http/route_users_test.go
> +func checkUserField(t *testing.T, data map[string]interface{}, field string, expected interface{}) {
我可以改成直接比對整個map response

2021-04-04 13:36 UTC, PichuChen commented
@gogog22510  好像有conflicts 要處理

2021-04-06 19:58 UTC, gogog22510 commented
> 請先按照 ISSUE 上面的實作，如果有其他要修改的請另外開 ISSUE 討論。

原本的功能已經有實作了，我照著ISSUE上所描述的，做了修改test case以及logging error的動作

2021-04-09 16:15 UTC, PichuChen reviewed
我現在看到他的 Files changed = 0 ，是我這邊有問題嗎？
<img width="706" alt="截圖 2021-04-10 上午12 14 17" src="https://user-images.githubusercontent.com/600238/114209862-b1f71600-9991-11eb-843b-dfd2b408d304.png">

2021-04-09 16:15 UTC, PichuChen commented on internal/delivery/http/route_users_test.go
> +	if !reflect.DeepEqual(responsedData, expectedData) {
他這個可以用原本 != 而不是用 DeepEqual 嗎？

2021-04-09 16:17 UTC, gogog22510 commented
我也看到change 0, 讓我研究看看.
!=無法比對map, 但deepequal可以

On Fri, Apr 9, 2021, 12:15 PM Pichu Chen ***@***.***> wrote:

> *@PichuChen* commented on this pull request.
>
> 我現在看到他的 Files changed = 0 ，是我這邊有問題嗎？
> [image: 截圖 2021-04-10 上午12 14 17]
> <https://user-images.githubusercontent.com/600238/114209862-b1f71600-9991-11eb-843b-dfd2b408d304.png>
> ------------------------------
>
> In internal/delivery/http/route_users_test.go
> <https://github.com/Ptt-official-app/Ptt-backend/pull/159#discussion_r606803096>
> :
>
> > @@ -39,9 +57,9 @@ func TestGetUserInformation(t *testing.T) {
>
>
>
>  	t.Logf("got response %v", rr.Body.String())
>
>  	responsedData := responsedMap["data"].(map[string]interface{})
>
> -	if responsedData["user_id"] != userID {
>
> -		t.Errorf("handler returned unexpected body, user_id not match: got %v want userId %v",
>
> -			rr.Body.String(), userID)
>
> +	if !reflect.DeepEqual(responsedData, expectedData) {
>
>
> 他這個可以用原本 != 而不是用 DeepEqual 嗎？
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ptt-official-app/Ptt-backend/pull/159#pullrequestreview-627540230>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4FGLQMMCNFB7PZOZRUQHTTH4R2LANCNFSM42IHPP6Q>
> .
>

2021-04-09 16:23 UTC, gogog22510 commented on internal/delivery/http/route_users_test.go
> +	if !reflect.DeepEqual(responsedData, expectedData) {
!=好像無法比對map，DeepEqual可以

2021-04-09 16:32 UTC, PichuChen commented
但是在寫測試上面，應該是直接把map用key比較會比較確定發生了什麼事？

2021-04-09 18:36 UTC, gogog22510 commented
改成比對key了

2021-04-12 15:45 UTC, PichuChen requested changes

2021-04-12 15:45 UTC, PichuChen commented on internal/delivery/http/route_users_test.go
> +				vstr := fmt.Sprintf("%v", val)
這邊可以實際列舉出需要被測試的 map-key-value 嗎？

2021-04-12 17:19 UTC, gogog22510 commented on internal/delivery/http/route_users_test.go
> +				vstr := fmt.Sprintf("%v", val)
上方有expectedData 裡面的key就是這裡比較的key，這樣還需要在這裡再列一遍嗎?

2021-04-13 04:29 UTC, PichuChen requested changes

2021-04-13 04:29 UTC, PichuChen commented on internal/delivery/http/route_users_test.go
> +				vstr := fmt.Sprintf("%v", val)
https://github.com/Ptt-official-app/Ptt-backend/pull/119/files#diff-49a931f7259c96ffeff2bf8fd342f27c16299464050c23c3fea0114e54ff2537R64

我覺得可以參考這個的寫法，主要是避免使用到reflect這樣

2021-04-13 13:46 UTC, gogog22510 commented on internal/delivery/http/route_users_test.go
> +				vstr := fmt.Sprintf("%v", val)
OK, 我會改成轉成json在做比對

2021-04-17 03:01 UTC, sonorous-lester approved these changes
LGTM

2021-04-17 08:41 UTC, PichuChen approved these changes
LGTM

2021-04-20 03:01 UTC, y2468101216 commented
LGTM

2021-04-20 05:43 UTC, merged