Feature/#152 forward article
Ptt-official-app/Ptt-backend pull request #169
Opened 2021-04-09 09:20 UTC by titaneric

## 👏 解決掉的 issue / Resolved Issues
- close #152 

## ⛏ 變更內容 / Details of Changes

### Route

- 在delivery/http/route.go中的`postBoards` method，針對action = "forward_article" 呼叫delivery.ForwardArticle
- 在delivery/http裡新增`route_forward_article.go`實作`ForwardArticle` method，呼叫usecase.ForwardArticle
- 在usecase/token.go 新增`PermissionForwardArticle` 權限
- 在uscase/usecase.go新增`ForwardArticle` method至Usecase interface
- 在usecase/article.go裡面新增`ForwardArticle` method

### Test

- 在delivery/http/route_article_test.go裡面新增`forwardArticle` mock test method
- 在delivery/http裡新增`route_forward_article_test.go`
- 更新swagger.yml action 內容

2021-04-11 17:23 UTC, PichuChen requested changes

2021-04-11 17:23 UTC, PichuChen commented on internal/usecase/usecase.go
> +	ForwardArticle(ctx context.Context, userID, boardID, filename, toEmail, toBoard string) (map[string]interface{}, error)
Email 和 Board 應該可以拆成兩個 method 比較好，一來是不太會同時兩個都填參數，而來是如果未來要新增新的 Forward 目標時，可以單純新增新的 method 這樣。

2021-04-11 17:25 UTC, PichuChen commented
related to #155

2021-04-12 01:41 UTC, y2468101216 requested changes

2021-04-12 01:41 UTC, y2468101216 commented on internal/delivery/http/route_forward_article.go
> +	toBoard := r.PostFormValue("board")
這邊用 PostFormValue 會不會與主流不同?一般不是使用 json 作為 body?

2021-04-12 01:42 UTC, PichuChen commented on internal/delivery/http/route_forward_article.go
> +	toBoard := r.PostFormValue("board")
請參考文件

2021-04-12 04:29 UTC, titaneric commented on internal/usecase/usecase.go
> +	ForwardArticle(ctx context.Context, userID, boardID, filename, toEmail, toBoard string) (map[string]interface{}, error)
沒問題，我改看看

2021-04-12 05:33 UTC, AmberFu commented on internal/usecase/token.go
> +	PermissionForwardArticle          Permission = "FORWARD_ARTICLE"
不是很確定 "轉錄目標看板" 是否要檢查該看板能否轉錄文章進來的權限？

2021-04-12 05:52 UTC, titaneric commented
@PichuChen 已修改，目前改成用interface， @AmberFu 在實作 #155 可以參考一下，雖然好像順便做掉了QQ。
對Golang還不算熟悉，有更好的方式請指正，謝謝。

2021-04-12 05:55 UTC, titaneric commented on internal/usecase/token.go
> +	PermissionForwardArticle          Permission = "FORWARD_ARTICLE"
感覺這也要檢查沒錯，轉出跟轉入的看板權限分清楚

2021-04-12 09:04 UTC, PichuChen commented on internal/usecase/token.go
> +	PermissionForwardArticle          Permission = "FORWARD_ARTICLE"
> 不是很確定 "轉錄目標看板" 是否要檢查該看板能否轉錄文章進來的權限？

看起來轉出權限是一個，然後轉入權限應該是檢查寫入權限？

2021-04-12 15:45 UTC, titaneric commented on internal/usecase/token.go
> +	PermissionForwardArticle          Permission = "FORWARD_ARTICLE"
寫入權限看起來沒有，感覺要自己新增

2021-04-13 04:22 UTC, PichuChen requested changes

2021-04-13 04:22 UTC, PichuChen commented on internal/usecase/token.go
> +	PermissionForwardArticleTo        Permission = "FORWARD_ARTICLE"
這邊兩個Key值一樣但是用了不一樣的變數名稱應該不太好？應該不用分Out和TO, 直接在註解下去說明這個權限主要是判斷可不可以轉出這樣？

2021-04-13 04:23 UTC, PichuChen commented on internal/usecase/token.go
> +	PermissionForwardArticle          Permission = "FORWARD_ARTICLE"
應該可以多一個 PermissionAddArticle 這樣？

2021-04-13 05:26 UTC, titaneric commented on internal/usecase/token.go
> +	PermissionForwardArticleTo        Permission = "FORWARD_ARTICLE"
Sorry，這邊有點寫錯，應該key要不一樣的，會照你意思新增`PermissionAddArticle``，我再試著修改。

2021-04-13 06:55 UTC, PichuChen commented on internal/usecase/usecase.go
> +	ForwardArticle(ctx context.Context, userID, boardID, filename string, to Forward) (map[string]interface{}, error)
這邊應該暫時還不需要這麼複雜...

Forward 另外拉成物件來實作的這件事應該要另外開ISSUE討論

2021-04-13 06:57 UTC, PichuChen commented on internal/usecase/usecase.go
> +	ForwardArticle(ctx context.Context, userID, boardID, filename string, to Forward) (map[string]interface{}, error)
```suggestion
	ForwardArticleToBoard(ctx context.Context, userID, boardID, filename string, boardName string) (map[string]interface{}, error)
	ForwardArticleToEmail(ctx context.Context, userID, boardID, filename string, email string) (map[string]interface{}, error)
```

2021-04-14 09:34 UTC, titaneric commented
@PichuChen 已更新

2021-04-14 10:36 UTC, PichuChen approved these changes
LGTM

2021-04-15 01:35 UTC, y2468101216 commented
LGTM

應該要討論一下轉板跟轉信是否要拆開成兩個API實作

2021-04-15 12:52 UTC, SivWatt approved these changes
LGTM

2021-04-15 12:59 UTC, merged

2021-04-15 13:01 UTC, PichuChen commented
> LGTM
> 
> 
> 
> 應該要討論一下轉板跟轉信是否要拆開成兩個API實作

在Usecase中確實是分兩個，其實本來就是分兩個，只是不小心在delivery做起來了