WIP: forward article repository
Ptt-official-app/Ptt-backend pull request #186
Opened 2021-04-17 09:32 UTC by RicoToothless

## 👏 解決掉的 issue / Resolved Issues
- close #154 

## 📝 相關的 issue / Related Issues
- #66 
- #152 
- #153
## ⛏ 變更內容 / Details of Changes

- add forward article repository

2021-04-17 09:37 UTC, RicoToothless commented
新手提問三個問題：
1. 請教為什麼 lint error `repository.Repository` missing method `ForwardArticleToBoard`？
2. 第一次寫 Go，是照前面的 PR 依樣畫葫蘆出來的，有沒有遺漏的地方？
3. 回應文章跟轉錄看板文章似乎有點像。
我實際去看 PTT，
回應文章 (y) 的確有分到看板跟信箱；
轉錄 (^X) 似乎只有轉到別的看板而已。
所以實作上，回應文章到看板跟轉錄是一樣的東西囉？

2021-04-17 10:18 UTC, nickyanggg commented
> 1. 請教為什麼 lint error `repository.Repository` missing method `ForwardArticleToBoard`？

因為 usecase/mock_test.go 中的 MockRepository 實作 repository.Repository，所以 MockRepository 也必須實作 Repository 定義的所有函式， 之前寫的人都是寫在 usecase/board_mock_test.go 和 usecase/user_mock_test.go 中

2021-04-19 08:03 UTC, y2468101216 commented
> 2. 第一次寫 Go，是照前面的 PR 依樣畫葫蘆出來的，有沒有遺漏的地方？
可以先跑 go build 看能不能 build 起來，build 不過肯定沒寫對
再來是跑 go test ./... 跑不過的肯定有問題

2021-04-21 14:29 UTC, RicoToothless commented
> 因為 usecase/mock_test.go 中的 MockRepository 實作 repository.Repository，所以 MockRepository 也必須實作 Repository 定義的所有函式， 之前寫的人都是寫在 usecase/board_mock_test.go 和 usecase/user_mock_test.go 中

我看了一下，所以我這個似乎要多寫一個 file 為 `usecase/article_mock_test.go` 囉？

2021-04-22 03:53 UTC, y2468101216 commented
> > 因為 usecase/mock_test.go 中的 MockRepository 實作 repository.Repository，所以 MockRepository 也必須實作 Repository 定義的所有函式， 之前寫的人都是寫在 usecase/board_mock_test.go 和 usecase/user_mock_test.go 中
> 
> 我看了一下，所以我這個似乎要多寫一個 file 為 `usecase/article_mock_test.go` 囉？

寫在 article_test.go 裡就好

2021-04-26 13:44 UTC, RicoToothless commented
我後來還是新增了 `usecase/article_mock_test.go` file

2021-04-27 06:54 UTC, y2468101216 requested changes

2021-04-27 06:54 UTC, y2468101216 commented on internal/usecase/article_mock_test.go
> +package usecase
將這個檔案改放在 board_mock_test.go

2021-04-27 09:09 UTC, PichuChen commented on internal/repository/article.go
> +	result := map[string]interface{}{
這邊應該要加上 TODO 然後串接實際上在該版新增文章的動作，以及在原文章底下加上被轉貼到某看板的紀錄？

2021-04-27 09:12 UTC, PichuChen requested changes

2021-04-27 09:12 UTC, PichuChen commented on internal/repository/article.go
> +	return nil
因為這個ISSUE應該時要實作 repository 所以這邊應該是要有東西？ 雖然forward 應該是由usecase 去轉寄到 email provider?

2021-04-28 13:08 UTC, RicoToothless commented on internal/repository/article.go
> +	result := map[string]interface{}{
所以是從 `map[string]interface{}` 改用這樣子嗎？
```golang
type ForwardArticleToBoardRecord interface {
	// Note: go-bbs has not implemented this yet
	// TODO: use bbs.ForwardArticleToBoardRecord or something when it is ready
	bbs.ArticleRecord
	BoardID() string
	forwardTime() time.Time
}

func (repo *repository) ForwardArticleToBoard(ctx context.Context, userID, boardID, filename, boardName string) ([]ForwardArticleToBoardRecord, error) {
	// Note: go-bbs has not implemented this yet
	// TODO: delegate to repo.db when it is ready
	return []ForwardArticleToBoardRecord{}, nil
}
```

2021-04-28 13:57 UTC, RicoToothless commented on internal/repository/article.go
> +	return nil
這邊之前就一直很困惑了，大概是這樣？
```golang
func (repo *repository) ForwardArticleToEmail(ctx context.Context, userID string, boardID string, filename string, email string) error {
	var repoConfig *config.Config
	mail.NewMail(repoConfig.MailDriver)
	return nil
}
```

2021-04-28 13:58 UTC, RicoToothless commented on internal/usecase/article_mock_test.go
> +package usecase
好，到時候一起改

2021-05-24 04:14 UTC, y2468101216 commented
fix by #203

2021-05-24 04:14 UTC, closed without merging