implement GetPopularBoards usecase and add mock test in board_mock_test
Ptt-official-app/Ptt-backend pull request #187
Opened 2021-04-20 10:34 UTC by whitefloor

## 👏 解決掉的 issue / Resolved Issues
- close #164 
- close #181 

## 📝 相關的 issue / Related Issues
- #51 

## ⛏ 變更內容 / Details of Changes

- usecase
1. 新增usecase method:GetPopularBoards
2. 新增usecase test:TestGetPopularBoards
3. 新增mock repo :GetPopularBoards

- #181 : 由於直接使用GetBoards取得資料再由usecase進行篩選，所以沒有新增function

2021-04-20 12:20 UTC, PichuChen requested changes

2021-04-20 12:20 UTC, PichuChen commented on internal/usecase/board.go
> +		return allBoards, errors.New("GetBoards error : No data")
如果 len == 0 的狀況，應該是可以寫 Warning, 但是不需要回傳 err, 在這邊回傳 err 的話有可能會回應 500 給 client

2021-04-20 12:20 UTC, PichuChen commented on internal/usecase/board.go
> +	filtedBoards := shouldBeDisplayOnPouplarList(&allBoards)
should 開頭的應該會是回傳 boolean?
所以理想的狀況應該是
```
filtedBoards := []bbs.BoardRecord{}
for _, b := range allBoards {
    if (shouldBeDis... (b)) {
        filtedBoards = append(filtededBoards, b)
    }

}
```
這樣？

2021-04-20 17:09 UTC, whitefloor commented on internal/usecase/board.go
> +	filtedBoards := shouldBeDisplayOnPouplarList(&allBoards)
我懂你的意思了，我改一下

2021-04-20 17:09 UTC, whitefloor commented on internal/usecase/board.go
> +		return allBoards, errors.New("GetBoards error : No data")
好的，這我改一下

2021-04-21 08:41 UTC, y2468101216 commented
感覺應該要增加一個有 popularboard 的 test 比較好

2021-04-21 15:43 UTC, whitefloor commented
> 感覺應該要增加一個有 popularboard 的 test 比較好

有啊＠＠ TestGetPopularBoards
還是你是說其他部分

2021-04-22 03:22 UTC, y2468101216 commented
> > 感覺應該要增加一個有 popularboard 的 test 比較好
> 
> 有啊＠＠ TestGetPopularBoards
> 還是你是說其他部分

我看了一下 route_boards_test.go 有補上測試有 popularboard 回傳的資料格式正不正確，所以這部分找時間在處理就好

LGTM

2021-04-25 10:24 UTC, PichuChen approved these changes
LGTM

2021-04-27 06:46 UTC, merged