增加 smtp provider 回傳
Ptt-official-app/Ptt-backend pull request #198
Opened 2021-04-27 09:36 UTC by y2468101216

## 👏 解決掉的 issue / Resolved Issues
- close #196

## 📝 相關的 issue / Related Issues
- #191 
- #0

## ⛏ 變更內容 / Details of Changes
增加 smtp provider

2021-04-28 08:28 UTC, y2468101216 commented
有幾個地方要討論的

1.  usecase.go 裡的 NewUsecase 在取得 mail provider 沒有地方可以回傳 error
2.  sendmail 不直接支援 tls sendmail ，必須用587 port 做跳轉
3. 郵件寄信者要寫誰

2021-04-29 03:48 UTC, PichuChen commented on internal/mail/mail.go
> +func NewMail(mailDriver string) (Mail, error) {
名字可以改一下嗎？ 例如 MailProvider 或是 Mailer 之類的，因為 NewMail 可能會和 Mail 混淆

2021-04-29 03:50 UTC, PichuChen commented on internal/mail/smtp.go
> +	if !isSet {
password 應該不是一定要設定的東西？

2021-04-29 03:52 UTC, PichuChen commented on internal/mail/smtp.go
> +func (s *smtpProvider) Send(email, title, userID string, body []byte) error {
```suggestion
func (s *smtpProvider) Send(from, to, title string, body []byte) error {
```
這邊應該用 Email 常見的定義方式會比較好？

2021-04-29 03:53 UTC, PichuChen commented on internal/mail/smtp.go
> +	err := smtp.SendMail(s.smtpURL.Host, s.plainAuth, userID+"@ptt-backend.com", to, body)
不要寫死 `@ptt-backend.com`

2021-04-29 03:54 UTC, PichuChen commented on internal/mail/mail.go
> +
if err != nil 
前面不用空一行

2021-04-29 05:59 UTC, y2468101216 commented on internal/mail/smtp.go
> +	if !isSet {
沒有 password 的 smtp 我不敢用，我覺得還是強制用戶要申請一個有密碼的 smtp

2021-04-29 06:00 UTC, y2468101216 commented on internal/mail/smtp.go
> +	err := smtp.SendMail(s.smtpURL.Host, s.plainAuth, userID+"@ptt-backend.com", to, body)
那要做在哪邊，config 裡面嗎

2021-04-29 19:39 UTC, PichuChen commented on internal/mail/smtp.go
> +	if !isSet {
他有可能是localhost, 用IP限制的Postman這樣

2021-04-30 19:35 UTC, SivWatt commented on internal/mail/mail.go
> +	fmt.Printf("call mail send with: %s, %s, %v", from, title, body)
這邊之後有考慮要用logger print嗎

2021-04-30 19:35 UTC, SivWatt commented on internal/mail/smtp.go
> +func createSMTP(url *url.URL) (*smtpProvider, error) {
我覺得這邊function name可以是`newSMTPProvider`

2021-04-30 19:35 UTC, SivWatt commented on internal/mail/smtp.go
> +	smtpURL   *url.URL
smtp 前綴好像跟struct name重複了

2021-05-03 04:27 UTC, y2468101216 commented on internal/mail/smtp.go
> +	smtpURL   *url.URL
不太理解

2021-05-03 04:29 UTC, y2468101216 commented on internal/mail/mail.go
> +	fmt.Printf("call mail send with: %s, %s, %v", from, title, body)
應該只是 for test 用

2021-05-03 05:00 UTC, SivWatt commented on internal/mail/smtp.go
> +	smtpURL   *url.URL
我想說structure name smtpProvider已經有smtp了，url name就不需要用smtp開頭。

2021-05-03 05:40 UTC, y2468101216 commented on internal/mail/smtp.go
> +	smtpURL   *url.URL
恩，有道理，我改一下

2021-05-03 05:46 UTC, y2468101216 commented on internal/mail/smtp.go
> +	err := smtp.SendMail(s.smtpURL.Host, s.plainAuth, userID+"@ptt-backend.com", to, body)
done

2021-05-03 05:46 UTC, y2468101216 commented on internal/mail/smtp.go
> +	if !isSet {
done

2021-05-03 05:46 UTC, y2468101216 commented on internal/mail/smtp.go
> +func createSMTP(url *url.URL) (*smtpProvider, error) {
done

2021-05-03 05:46 UTC, y2468101216 commented on internal/mail/smtp.go
> +	smtpURL   *url.URL
done

2021-05-03 16:49 UTC, SivWatt commented on internal/mail/smtp.go
> +	hostSlice := strings.Split(url.Host, ":")
抱歉 之前沒看到這個 Orz
[URL.Hostname](https://golang.org/pkg/net/url/#URL.Hostname) 可以拿到去掉 Port 的 host

2021-05-03 16:50 UTC, SivWatt commented
>     1. usecase.go 裡的 NewUsecase 在取得 mail provider 沒有地方可以回傳 error
> 
`newSMTPProvider()` function 裡面現在看起來不會產生 error 我覺得這種情況就可以不用return error 
這樣Usecase 那邊就不用擔心要處理 error 了 _(之前應該是拿來 return 沒有password 的情況)_

2021-05-04 01:19 UTC, y2468101216 commented
> > ```
> > 1. usecase.go 裡的 NewUsecase 在取得 mail provider 沒有地方可以回傳 error
> > ```
> 
> 以現況來說 parse url fail 會回一個error 如果這會讓後面的功能走不下去 `NewUsecase` 就應該也要回error
> 不然後面拿nil 的mail去Send也遲早會 panic
> 
> 另外，`newSMTPProvider()` function 裡面現在看起來不會產生 error 我覺得這種情況就可以不用return error
> 
> > ```
> > 2. sendmail 不直接支援 tls sendmail ，必須用587 port 做跳轉
> > ```
> 
> [Example 1](https://gist.github.com/jim3ma/b5c9edeac77ac92157f8f8affa290f45)
> [Example 2](https://gist.github.com/chrisgillis/10888032)
> 這邊有兩個tls 的example 不過我沒有實際測過，類似的我只玩過FTP XD

這個問題其實是應該要改為是否要改為使用 tls，因為其實發信這件事情是 server to server，被中間人攻擊的可能性較低

2021-05-05 10:19 UTC, PichuChen requested changes

2021-05-05 10:19 UTC, PichuChen commented on internal/mail/mail.go
> +//stmp example - smtp://username:password@mail.smtp.com:25
```suggestion
// NewMailProvider returns a SMTP mail provider with connection string. Eg, smtp://username:password@example.com:25
//
// The password is required right now.
```

2021-05-05 10:19 UTC, PichuChen commented on internal/usecase/usecase.go
> -		mail:         mail.NewMail(globalConfig.MailDriver),
這個參數感覺也要被改成 `mailProvider`

2021-05-05 10:19 UTC, PichuChen commented on internal/usecase/usecase.go
> -		mail:         mail.NewMail(globalConfig.MailDriver),
或是 `mp` 會比較好嗎？

2021-05-07 05:12 UTC, y2468101216 commented on internal/usecase/usecase.go
> -		mail:         mail.NewMail(globalConfig.MailDriver),
改成 mailProvider 吧，mp 還真不知道表達啥

2021-05-12 08:18 UTC, PichuChen approved these changes
LGTM

2021-05-12 08:19 UTC, merged