根據 whitefloor 調整了既有的說明文檔
Ptt-official-app/Ptt-backend pull request #200
Opened 2021-04-28 06:40 UTC by y2468101216

## 👏 解決掉的 issue / Resolved Issues
- close #151

## ⛏ 變更內容 / Details of Changes
根據 whitefloor 調整了一些文檔上的問題

主要的更動如下:

1. 將歷史緣由跟開發原因搬進 FOR_DEVELOPERS.md 裡面

我覺得作為一個專案的門面，應當盡量簡單扼要說明這個專案的的功能。

2. 直接增加了如何參與這個專案

由於希望此專案不要變成一人開發，需要用更簡單的方法吸引人進來參與

3. 增加了 Q&A 

我將 Q&A 拆成了兩個 part ，一個是給要深入專案的，一個是給第一次參與的

2021-04-28 08:04 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +的主因在於便於其他開發者進行開發，HTTP有許多現成的客戶端以及測試工具，在各種語言以及平台中皆有範例程式碼以及函式庫可以呼叫。
建議 README 內容如果有中英文交叉出現的地方，可以前後各空一格，維持一致的寫作風格。
例如以上可以改成 : 
```
HTTP 有許多現成的客戶端以及測試工具
```

2021-04-30 02:09 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +（也就是傳統可以用 PCMAN 登入的 BBS 介面）的SSH連線方式。
`SSH`連線方式 <- 沒改到

2021-04-30 02:16 UTC, unknowntpo commented on README.md
> +Ptt-backend 是做 BBS (Bulletin Board System)的開源專案
這裡可以改成
```
- Ptt-backend 是做 BBS (Bulletin Board System)的開源專案
+ Ptt-backend 是做 BBS(Bulletin Board System) 的開源專案
```

2021-04-30 02:17 UTC, unknowntpo requested changes
另外，我找到了一份關於中英交叉的 README 怎麼寫的 github repo ，給大家參考。

- [sparanoid / chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)

還有，這份是關於 README 如何排版的指引。

- [RichardLitt / standard-readme](https://github.com/RichardLitt/standard-readme#example-readmes)

2021-04-30 02:52 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +原有的 [PTT 程式碼](https://github.com/ptt/pttbbs)是透過C語言進行開發的，
```
- 原有的 [PTT 程式碼](https://github.com/ptt/pttbbs)是透過C語言進行開發的，
+ 原有的 [PTT 程式碼](https://github.com/ptt/pttbbs) 是透過 C 語言進行開發的，
```

2021-04-30 02:54 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +另外HTTPS也經過了數年來在資訊安全上的驗證，同時我們可以透過 HTTP 既有的快取機制設計來進一步節省維運伺服器所需要的流量。
```
- 另外HTTPS也經過了數年來在資訊安全上的驗證，同時我們可以透過 HTTP 既有的快取機制設計來進一步節省維運伺服器所需要的流量。
+ 另外 HTTPS 也經過了數年來在資訊安全上的驗證，同時我們可以透過 HTTP 既有的快取機制設計來進一步節省維運伺服器所需要的流量。
```

2021-04-30 02:55 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +====外面（公有 IP 或是受防火牆保護的網段）=====
==== 外面（公有 IP 或是受防火牆保護的網段）=====

2021-04-30 02:55 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +解開傳入的 Access Token, 取出使用者必要資訊（例如User ID, User Level）
```
- 解開傳入的 Access Token, 取出使用者必要資訊（例如User ID, User Level）
+ 解開傳入的 Access Token, 取出使用者必要資訊（例如 User ID, User Level）
```

2021-04-30 03:00 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +Ptt-backend的 部分通常是實作 delivery/usecase/repository/ 以及這三個的 test
Ptt-backend 的部分通常是實作 
- `internal/repository/` 
- `internal/usecase/`
- `internal/delivery/`

以及這三個 layer 的測試。

2021-04-30 03:01 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +* 我會寫程式,但是 query 找不到
```
- * 我會寫程式,但是 query 找不到
+ * 我會寫程式，但是 query 找不到
```

2021-05-03 10:50 UTC, unknowntpo reviewed
還有一小部分沒有改到。

2021-05-03 10:50 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +解開傳入的 Access Token, 取出使用者必要資訊（例如User ID, User Level）
```
- 解開傳入的 Access Token, 取出使用者必要資訊（例如User ID, User Level）
+ 解開傳入的 Access Token, 取出使用者必要資訊（例如 User ID, User Level)
```

2021-05-03 10:50 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +* 我會寫程式,但是 query 找不到
```
- * 我會寫程式,但是 query 找不到
+ * 我會寫程式，但是 query 找不到
```

2021-05-03 10:50 UTC, unknowntpo commented on FOR_DEVELOPERS.md
> +Ptt-backend的 部分通常是實作 delivery/usecase/repository/
```
- Ptt-backend的 部分通常是實作 delivery/usecase/repository/ 
+ Ptt-backend 的部分通常是實作 delivery/usecase/repository/ 
```

2021-05-04 14:05 UTC, PichuChen approved these changes
LGTM

2021-05-04 14:05 UTC, PichuChen commented on README.md
> +1. 要有個 github 帳號
GitHub

2021-05-05 08:36 UTC, y2468101216 commented on README.md
> +1. 要有個 github 帳號
done

2021-05-07 05:19 UTC, y2468101216 commented
@unknowntpo 如果沒問題再麻煩妳看看

2021-05-10 11:53 UTC, unknowntpo reviewed
剩下這些地方

2021-05-10 11:53 UTC, unknowntpo commented on README.md
> +但 BBS 有很多種, Ptt 只是 BBS 的其中一種
```
- 但 BBS 有很多種, Ptt 只是 BBS 的其中一種
+ 但 BBS 有很多種，Ptt 只是 BBS 的其中一種
```

2021-05-10 11:53 UTC, unknowntpo commented on README.md
> +go-bbs 是與 Ptt-backend 有關的專案,解析儲存的檔案提供給 Ptt-backend 使用
```
- go-bbs 是與 Ptt-backend 有關的專案,解析儲存的檔案提供給 Ptt-backend 使用
+ go-bbs 是與 Ptt-backend 有關的專案，解析儲存的檔案提供給 Ptt-backend 使用

2021-05-12 08:19 UTC, merged