feat: forward article usecase & repository
Ptt-official-app/Ptt-backend pull request #203
Opened 2021-05-07 12:51 UTC by RicoToothless

## 👏 解決掉的 issue / Resolved Issues
- close #154

## 📝 相關的 issue / Related Issues
- #66 
- #152 
- #153 

## ⛏ 變更內容 / Details of Changes

- add forward article usecase
- add forward article repository

2021-05-09 19:29 UTC, gogog22510 requested changes

2021-05-09 19:29 UTC, gogog22510 commented on internal/usecase/article.go
> +	err = usecase.checkForwardArticlePermission(token,
這裡先做了forward後再檢查permission好像順序錯了?
我覺得檢查permission好像在http那邊做比較好或是那裏已經檢查過了?

2021-05-10 16:58 UTC, RicoToothless commented on internal/usecase/article.go
> +	err = usecase.checkForwardArticlePermission(token,
1. 順序錯了的確如此，到時候修正。
2. http 那邊的確有做 permission check，我是看 #153 寫說要 check permission，或者有什麼建議嗎？不太知道 usecase 要怎樣寫才正確有效。

2021-05-14 11:01 UTC, RicoToothless commented on internal/usecase/article.go
> +	err = usecase.checkForwardArticlePermission(token,
我這邊有更新一版

2021-05-20 07:50 UTC, y2468101216 requested changes

2021-05-20 07:50 UTC, y2468101216 commented on internal/delivery/http/route_articles_test.go
> +func (usecase *MockUsecase) ForwardArticleToBoard(ctx context.Context, userID, boardID, filename, boardName string) (repository.ForwardArticleToBoardRecord, error) {
為何是 filename 不是 article_id ? 要轉錄文章不是應該要該文章的 id 的嗎？

2021-05-20 07:51 UTC, y2468101216 commented on internal/delivery/http/route_articles_test.go
> +func (usecase *MockUsecase) ForwardArticleToBoard(ctx context.Context, userID, boardID, filename, boardName string) (repository.ForwardArticleToBoardRecord, error) {
我看文件上面 route 也是 POST /v1/boards/{{board_id}}/articles/{{article_id}} 所以應該是 article_id?

2021-05-20 18:35 UTC, PichuChen commented on internal/delivery/http/route_articles_test.go
> +func (usecase *MockUsecase) ForwardArticleToBoard(ctx context.Context, userID, boardID, filename, boardName string) (repository.ForwardArticleToBoardRecord, error) {
這問題很好，filename 的話有可能是 ArticleID 或是 TreasureID 這樣？ 或者是非 Article 的東西

2021-05-20 18:38 UTC, PichuChen approved these changes
LGTM

2021-05-21 08:30 UTC, merged