feat: Implement mailgun provider
Ptt-official-app/Ptt-backend pull request #207
Opened 2021-05-14 17:48 UTC by SivWatt

## 👏 解決掉的 issue / Resolved Issues
- close #197 

## 📝 相關的 issue / Related Issues
- #191 

## ⛏ 變更內容 / Details of Changes

- `mail.go` - 新增 case 呼叫新增 mailgun provider
- `mail_test.go` - 新增兩個測試關於 `NewMailProvider()`
- `mailgun.go` - mailgun provider 實作
- `mailgun_test.go` - 測試 mailgun provider

## 其他
關於 mailgun provider test，我是用自己起一個 https server 的作法去測，這樣 Send 成功以及失敗就都可以被測到。
測試成功的部份有在 handler function 裡面對 request 做一些檢查，如果覺得這個部分不需要，其實也可以拿掉。

2021-05-16 02:25 UTC, y2468101216 requested changes

2021-05-16 02:25 UTC, y2468101216 commented on internal/mail/mailgun.go
> +	if notGood(resp.StatusCode) {
只須判斷200就好，我看 mailgun api 文件也是只有 200 才算成功。
200以外的不要判斷，避免它新增了其他含意 statu code

2021-05-16 02:25 UTC, y2468101216 commented on internal/mail/mailgun.go
> +}
只須判斷 200 就好，所以這個該移除

2021-05-16 02:25 UTC, y2468101216 commented on internal/mail/mail_test.go
> +func TestNewMailProvider_WithSMTP(t *testing.T) {
我記得不是已經有一個 smtp_test.go 了嗎?
不需要特別為了 mail 去寫重複的測試

2021-05-16 02:25 UTC, y2468101216 commented on internal/mail/mail_test.go
> +func TestNewMailProvider_WithMailgun(t *testing.T) {
同上

2021-05-16 06:46 UTC, SivWatt commented on internal/mail/mailgun.go
> +	if notGood(resp.StatusCode) {
好啊 這段是我從他的go sdk抄過來的 因為我沒真的打過也不知道會回哪些
我再改一下

2021-05-16 06:57 UTC, SivWatt commented on internal/mail/mail_test.go
> +func TestNewMailProvider_WithSMTP(t *testing.T) {
這個部份是我個人的想法 我有在PR message 提到。
差別就是 smtp_test 是 call NewMailProvider()  mailgun_test 是 call newMailgunProvider()  
這邊其實也沒有所謂的對錯 單純就是 test 要寫在哪裡

2021-05-17 02:33 UTC, y2468101216 commented on internal/mail/mail_test.go
> +func TestNewMailProvider_WithSMTP(t *testing.T) {
如果是這樣的話我就沒有意見，我覺得都可以

2021-05-17 03:58 UTC, SivWatt commented on internal/mail/mail_test.go
> +func TestNewMailProvider_WithSMTP(t *testing.T) {
我也覺得都可以XD 
所以先做上來 蒐集大家的想法

2021-05-17 14:03 UTC, SivWatt commented on internal/mail/mailgun.go
> +	if notGood(resp.StatusCode) {
改好了

2021-05-17 14:03 UTC, SivWatt commented on internal/mail/mailgun.go
> +}
改好了

2021-05-18 01:21 UTC, y2468101216 commented
LGTM
@PichuChen

2021-05-18 13:37 UTC, PichuChen approved these changes
LGTM

2021-05-18 13:37 UTC, merged