impliment preference by pttbbs api
Ptt-official-app/Ptt-backend pull request #229
Opened 2021-06-20 18:02 UTC by PichuChen

## 👏 解決掉的 issue / Resolved Issues
- close #218 

## 📝 相關的 issue / Related Issues
- #148 
- #150 
- #62

## ⛏ 變更內容 / Details of Changes
- 因為 go-bbs 還沒確定相關的 Interface 如何實作，因此先判斷為 pttbbs 後直接透過 flag 來取得設定

2021-06-21 04:20 UTC, y2468101216 requested changes

2021-06-21 04:20 UTC, y2468101216 commented on internal/repository/user_test.go
> +
別在 TestGetUserArticles 裡測試取得 GetUserPreferences，兩個測試混在一起到時出錯 debug 會很難判斷是哪邊出錯錯

2021-06-26 01:37 UTC, PichuChen commented on internal/repository/user_test.go
> +
這個大概是寫到睡著了， Test的標題寫錯了，應該要寫成 TestGetUserPreferences

2021-06-28 03:07 UTC, nickyanggg approved these changes
LGTM

2021-06-30 07:28 UTC, y2468101216 commented
LGTM

2021-06-30 07:29 UTC, merged