Feat/search articles
Ptt-official-app/Ptt-backend pull request #24
Opened 2021-01-31 10:15 UTC by ars0915

## 👏 解決掉的 issue / Resolved Issues
- #13 
- #14 

## 📝 相關的 issue / Related Issues
NA

## ⛏ 變更內容 / Details of Changes

- /v1/boards/{{board_id}}/articles 取得看版內文章列表的部份加上參數 author 或 title 或是兩者皆搜尋

2021-01-31 12:28 UTC, ggary9424 commented
有關 case insensitive，author 和 title 的 query parameters 應該也要做 lowercase 再做比對

2021-01-31 13:00 UTC, PichuChen commented
會有興趣補上 testing 嗎？

2021-01-31 13:06 UTC, ars0915 commented
> 會有興趣補上 testing 嗎？
好的，晚點補

2021-01-31 22:15 UTC, Julian-Chu commented on route_borads_articles.go
>  			"filename": f.Filename(),
這邊應該可以定義一個struct去接ArticleRecord，看起來欄位是固定的。對後續相關有用到Article的功能會有比較好的一致性，test case也會比較好寫一點

2021-02-01 00:35 UTC, PichuChen commented on route_borads_articles.go
>  			"filename": f.Filename(),
這個我覺得可以討論，struct 的話好處是後面拼字錯誤可能會比較少、然後效能不確定有沒有比較高，缺點應該是變成要另外補上 field tag `json:"filename"` 另外是假如不同狀況要輸出不同欄位時要修改的地方可能會變多。

2021-02-01 02:15 UTC, ars0915 commented on route_borads_articles.go
>  			"filename": f.Filename(),
目前的需求看起來會有需要 article 輸出不同欄位的時候嗎?

2021-02-01 08:46 UTC, Julian-Chu commented on route_borads_articles.go
>  			"filename": f.Filename(),
效能的部分 我印象struct比較高，晚點來寫benchmark看看， 還想到struct有另一個優點是 如果要做input validation,  可以直接把他放在struct 的tag裡，

2021-02-01 10:35 UTC, PichuChen commented on route_borads_articles.go
>  			"filename": f.Filename(),
> 目前的需求看起來會有需要 article 輸出不同欄位的時候嗎?

有可能不同的使用者權限會看到不同的欄位值這樣，因為這個原因所以後來我預設都用 m["key"] = value 的做法比較簡單，如果要刪除的話那也只要 delete(m, "key") 就行了。

2021-02-01 16:31 UTC, Julian-Chu commented on route_borads_articles.go
>  			"filename": f.Filename(),
FYI　benchmark:  map vs struct,  Marschal vs MarschIndent
```
Benchmark_MarshalIndent_MapToBytes-8             33123        35843 ns/op       14180 B/op       203 allocs/op
Benchmark_MarshalIndent_StructToBytes_1-8        69679        14930 ns/op        7225 B/op        33 allocs/op
Benchmark_MarshalIndent_StructToBytes_2-8        79028        14766 ns/op        8154 B/op        27 allocs/op
Benchmark_MarshalIndent_StructToBytes_3-8        90169        13239 ns/op        6954 B/op        12 allocs/op
Benchmark_Marshal_MapToBytes-8                   46640        25062 ns/op        9641 B/op       197 allocs/op
Benchmark_Marshal_StructToBytes_1-8             221845         5257 ns/op        2690 B/op        27 allocs/op
Benchmark_Marshal_StructToBytes_2-8             231732         5040 ns/op        3619 B/op        21 allocs/op
Benchmark_Marshal_StructToBytes_3-8             324344         3632 ns/op        2418 B/op         6 allocs/op
Benchmark_Unmarshal_ToMap-8                      78315        14794 ns/op        5112 B/op       150 allocs/op
Benchmark_Unmarshal_ToStruct-8                   78730        15071 ns/op        2608 B/op        43 allocs/op
```
https://github.com/Julian-Chu/go-Marshal-testing#go-marshal-testing
Marshal vs MarshalIndent差異比我想的還要大，也許另開一個issue跟struct一起討論?
這個PR就保持map就好

2021-02-06 13:18 UTC, PichuChen commented
想問一下目前這個 PR 的狀態到哪邊了？

2021-02-06 13:31 UTC, ars0915 commented
> 想問一下目前這個 PR 的狀態到哪邊了？

 功能開發完了，剩 rebase 更新 clean architecture 的部份， 還有補上測試。

2021-02-06 16:14 UTC, ars0915 commented
@PichuChen 目前在寫 usecase 測試時遇到一個 import cycle 的問題
```
import cycle not allowed in test
package github.com/Ptt-official-app/Ptt-backend/internal/usecase (test)
        imports github.com/Ptt-official-app/Ptt-backend/internal/mock
        imports github.com/Ptt-official-app/Ptt-backend/internal/usecase
FAIL    github.com/Ptt-official-app/Ptt-backend/internal/usecase [setup failed]
```
是不是該調整一下 mock repository 的位置，這樣之後才有辦法在 usecase 測試中 mock

2021-02-07 06:18 UTC, PichuChen commented
> @PichuChen 目前在寫 usecase 測試時遇到一個 import cycle 的問題
> 
> ```
> import cycle not allowed in test
> package github.com/Ptt-official-app/Ptt-backend/internal/usecase (test)
>         imports github.com/Ptt-official-app/Ptt-backend/internal/mock
>         imports github.com/Ptt-official-app/Ptt-backend/internal/usecase
> FAIL    github.com/Ptt-official-app/Ptt-backend/internal/usecase [setup failed]
> ```
> 
> 是不是該調整一下 mock repository 的位置，這樣之後才有辦法在 usecase 測試中 mock

要和 @mkfsn  確認一下，因為目前新的程式碼架構主要是他那邊提的

2021-02-08 01:29 UTC, ars0915 commented
> > @PichuChen 目前在寫 usecase 測試時遇到一個 import cycle 的問題
> > ```
> > import cycle not allowed in test
> > package github.com/Ptt-official-app/Ptt-backend/internal/usecase (test)
> >         imports github.com/Ptt-official-app/Ptt-backend/internal/mock
> >         imports github.com/Ptt-official-app/Ptt-backend/internal/usecase
> > FAIL    github.com/Ptt-official-app/Ptt-backend/internal/usecase [setup failed]
> > ```
> > 
> > 
> > 是不是該調整一下 mock repository 的位置，這樣之後才有辦法在 usecase 測試中 mock
> 
> 要和 @mkfsn 確認一下，因為目前新的程式碼架構主要是他那邊提的
> 
> 然後我不確定 mock 是不是需要獨立的 package, 如果是我的話，我會把 mock 的程式碼放在同個 package 然後名為 _test.go 的檔案底下。

之前的做法比較像是 repository 裡面放 board_mock.go user_mock.go 把原本在 mock/repository.go 的東西拆到各功能的 _mock.go

2021-02-08 16:06 UTC, PichuChen commented
> > > @PichuChen 目前在寫 usecase 測試時遇到一個 import cycle 的問題
> > > ```
> > > import cycle not allowed in test
> > > package github.com/Ptt-official-app/Ptt-backend/internal/usecase (test)
> > >         imports github.com/Ptt-official-app/Ptt-backend/internal/mock
> > >         imports github.com/Ptt-official-app/Ptt-backend/internal/usecase
> > > FAIL    github.com/Ptt-official-app/Ptt-backend/internal/usecase [setup failed]
> > > ```
> > > 
> > > 
> > > 是不是該調整一下 mock repository 的位置，這樣之後才有辦法在 usecase 測試中 mock
> > 
> > 
> > 要和 @mkfsn 確認一下，因為目前新的程式碼架構主要是他那邊提的
> > 然後我不確定 mock 是不是需要獨立的 package, 如果是我的話，我會把 mock 的程式碼放在同個 package 然後名為 _test.go 的檔案底下。
> 
> 之前的做法比較像是 repository 裡面放 board_mock.go user_mock.go 把原本在 mock/repository.go 的東西拆到各功能的 _mock.go

建議是可以在 _mock 後面再加上 _mock_test 如果這邊的內容只是要在 test 跑的話，這樣可以減少 binary 的大小

2021-02-09 15:56 UTC, PichuChen requested changes

2021-02-09 15:56 UTC, PichuChen commented on internal/usecase/board.go
> +				(cond.RecommendCountGe < 0 && f.Recommend() <= cond.RecommendCountGe)) {
因為我們有 Le 的設定，因此應該不需要 < 0 作為 Le ，另外考慮有人可能希望知道 > -20 的文章，因此建議改為以下程式。

```suggestion
				(cond.RecommendCountLe > 0 && f.Recommend() <= cond.RecommendCountLe)) {
```

2021-02-09 15:56 UTC, PichuChen commented on internal/usecase/board_test.go
> +				RecommendCountGe: -10,
所以這個可能要修改成
```suggestion
				RecommendCountLe: 10,
```

2021-02-09 15:56 UTC, PichuChen commented on internal/usecase/board.go
> +	RecommendCountGe int
照文件來說應該會有其他條件這樣
<img width="703" alt="截圖 2021-02-09 下午11 50 34" src="https://user-images.githubusercontent.com/600238/107389268-9d350800-6b31-11eb-812f-329a18b1e4ef.png">

2021-02-09 15:56 UTC, PichuChen commented on internal/delivery/http/route_boards_articles_test.go
> +	url := fmt.Sprintf("/v1/boards/test/articles?title=%s&author=%s&recommend_count_ge=%s", title, author, recommendCountGe)
可以考慮用 `net/url` `Values` 來組裝參數。

https://golang.org/pkg/net/url/#Values

2021-02-09 17:13 UTC, ars0915 commented on internal/usecase/board.go
> +	RecommendCountGe int
> 照文件來說應該會有其他條件這樣
> <img alt="截圖 2021-02-09 下午11 50 34" width="703" src="https://user-images.githubusercontent.com/600238/107389268-9d350800-6b31-11eb-812f-329a18b1e4ef.png">

你的意思是要這些參數都帶嗎？因為以功能上來說好像只會有 le 和 ge，而且他們也不能同時出現

2021-02-09 17:25 UTC, PichuChen commented on internal/usecase/board.go
> +	RecommendCountGe int
例如 le 50 ge 30 這樣就同時出現了

2021-02-09 17:47 UTC, ars0915 commented on internal/usecase/board.go
> +				(cond.RecommendCountGe < 0 && f.Recommend() <= cond.RecommendCountGe)) {
> 因為我們有 Le 的設定，因此應該不需要 < 0 作為 Le ，另外考慮有人可能希望知道 > -20 的文章，因此建議改為以下程式。

目前 Ptt 功能上是輸入負數就找尋噓文數以上的文章，這樣有需要做到 > -20 的部份嗎？還是你的 > -20 是指噓文數 > 20？
另外要做的話，以建議的程式來看是不是代表 Le 預設就是尋找噓文數？

不過 Le > 0 && Recommend <= Le 的判斷有點怪。Le > 0 會導致結果為 推/噓文數 <= 某個正數。
似乎也無法找尋 > -20 的文章，還是我有誤會你的意思＠＠

2021-02-09 19:31 UTC, PichuChen commented on internal/usecase/board.go
> +				(cond.RecommendCountGe < 0 && f.Recommend() <= cond.RecommendCountGe)) {
輸入負數找噓文數以上的文章是前端的設計，後端這邊做到和文件一致應該就行了。

應該不用另外判斷 Le > 0, 但是可能要判斷 Le != nil 或是其他方式代表進來的條件有 Le

2021-02-10 15:51 UTC, PichuChen requested changes

2021-02-10 15:51 UTC, PichuChen commented on internal/usecase/board.go
> +		if strings.Contains(strings.ToLower(f.Title()), strings.ToLower(cond.Title)) &&
使用者不一定要所有東西同時都要搜尋，他可以分開進行，例如他不限制作者或是不限制標題。

2021-02-10 16:17 UTC, ars0915 commented on internal/usecase/board.go
> +		if strings.Contains(strings.ToLower(f.Title()), strings.ToLower(cond.Title)) &&
如果那個條件沒帶的話這邊會是空字串，所以會是 true

2021-02-10 16:23 UTC, PichuChen commented on internal/usecase/board.go
> +		if strings.Contains(strings.ToLower(f.Title()), strings.ToLower(cond.Title)) &&
然後不建議把 && || 放在同一個 if 寫這麼長，會看到花掉

2021-02-10 16:25 UTC, PichuChen commented on internal/usecase/board.go
> +		if strings.Contains(strings.ToLower(f.Title()), strings.ToLower(cond.Title)) &&
```suggestion
		if !strings.Contains(strings.ToLower(f.Title()), strings.ToLower(cond.Title)) {
		        continue
		}
```

這樣應該會比較有可讀性？

2021-02-10 16:28 UTC, PichuChen commented on internal/usecase/board_test.go
> +		},
可以在幫我增加一個只設定標題 `Unicode` 
一個只設定作者 `sysop` 
的測試條件嗎？

2021-02-10 16:30 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +		RecommendCountGe:      recommendCountGe,
Ge 如果是指 greater equal 的縮寫的話，用 GE 會不會比較符合 lint 需求？
或者是值些使用全寫 RecommendCountGreaterEqual

2021-02-10 17:45 UTC, PichuChen approved these changes
LGTM

2021-02-10 21:08 UTC, Julian-Chu commented on internal/delivery/http/route_boards_articles.go
> +			"items": delivery.usecase.GetBoardArticles(context.Background(), boardId, searchCond),
GetBoardArticles回傳nil的情況，json上items應該是[]還是null? 要確認一下API文件

2021-02-10 21:08 UTC, Julian-Chu commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqualParam := queryParam.Get("recommend_count_ge")
recommend_count_ge , author...等常用字串 建議改成const，避免打字錯誤

2021-02-10 21:08 UTC, Julian-Chu commented on internal/usecase/board.go
> +		if cond.RecommendCountGreaterEqualIsSet && !(f.Recommend() >= cond.RecommendCountGreaterEqual) {
改成 f.Recommend() <  cond.RecommendCountGreaterEqual 比較直觀

2021-02-10 21:08 UTC, Julian-Chu commented on internal/usecase/board.go
> +		if cond.RecommendCountLessEqualIsSet && !(f.Recommend() <= cond.RecommendCountLessEqual) {
同上

2021-02-11 03:49 UTC, ars0915 commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqualParam := queryParam.Get("recommend_count_ge")
reommend_count_ge 這種參數應該不會常用到吧，如果像 author 要設成常數的話，usecase 回傳的 map key 是不是都要用常數？

2021-02-11 08:46 UTC, Julian-Chu commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqualParam := queryParam.Get("recommend_count_ge")
我表達的不精準，這些字串在boards handler的query parameter會常用到，預期business logic, test BadRequest, test OK 最少三次。加上recommend_count_get算是比較長的字串 ，可以避免打錯字或是後續萬一要修改名稱時需要同時更動多個地方。(ps: ，這邊的const只給這個handler或是http pkg內使用)
usecase這個要看一下了，多半的key可能只用一次，之後也可能回傳struct，有遇到在討論瞜

2021-02-11 08:53 UTC, ars0915 commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqualParam := queryParam.Get("recommend_count_ge")
嗯嗯 可以理解你的考量，的確recommend_count_ge 很容易打錯，不過這樣為了統一性是不是其他API的參數也都要 const 呢？還有 recommend_count_ge 這些，目前能想到的好像也只有這支 API 會用到耶

2021-02-11 09:05 UTC, Julian-Chu commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqualParam := queryParam.Get("recommend_count_ge")
雖然看起來只有這支API用到，不過還有相關測試也會用到。
我看了一下code，目前只會重複用兩次，其實可以暫時忽略，這邊就看你的決定了。

2021-02-12 07:07 UTC, ars0915 commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqualParam := queryParam.Get("recommend_count_ge")
這部份覺得等之後有再用到的話，再調整成 const

2021-02-12 07:07 UTC, ars0915 commented on internal/delivery/http/route_boards_articles.go
> +			"items": delivery.usecase.GetBoardArticles(context.Background(), boardId, searchCond),
這個感覺是 [] 比較好，不過要調的話是不是其他 API 也統一會比較好？

2021-02-12 07:17 UTC, PichuChen approved these changes
LGTM

2021-02-12 07:19 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +			"items": delivery.usecase.GetBoardArticles(context.Background(), boardId, searchCond),
應該是 [] 比較好，所以說 GetBoardArticles 要增加函式註解去解釋什麼情況他會回傳 nil (應該是沒有?)

目前 GetBoardArticles 沒有回傳 error 嗎？

2021-02-12 07:32 UTC, ars0915 commented on internal/delivery/http/route_boards_articles.go
> +			"items": delivery.usecase.GetBoardArticles(context.Background(), boardId, searchCond),
目前 error 是參數有錯誤或前面 permission 檢查沒過才會回傳，剛剛發現是我的錯QQ，把 item 宣告改成 `var item []interface{}` 會造成 nil slice，目前改回 `item := []interface{}{}` json 回傳就是 [] 了

2021-02-12 07:38 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +			"items": delivery.usecase.GetBoardArticles(context.Background(), boardId, searchCond),
目前 GetBoardArticles 的函式簽名應該是沒有 error, 所以我開了 ISSUE

2021-02-12 07:57 UTC, Julian-Chu approved these changes
LGTM

2021-02-12 07:58 UTC, merged