Added UpdateUsefuleness in usecase (wait for repo's function)
Ptt-official-app/Ptt-backend pull request #268
Opened 2021-08-15 20:08 UTC by kyho4515

## 👏 解決掉的 issue / Resolved Issues
- close #231

## 📝 相關的 issue / Related Issues
- #210
- #232

## ⛏ 變更內容 / Details of Changes

- 增加usecase裏的UpdateUsefulness
- test code還未實作，等repo的function完成，再新增

2021-08-16 02:09 UTC, y2468101216 commented on internal/usecase/article.go
> +		Title: filename,
傳起來的到底是 filename 還是 title ，這兩個不一樣歐。

2021-08-16 04:14 UTC, kyho4515 commented on internal/usecase/article.go
> +		Title: filename,
(好像有人提到Title跟filename是不一樣的，我寫的時候好像有注意到，但放到後來就忘了)
我這邊想要取file header(article record)，但search cond沒有提供用filename來搜
我可以想到的解法有兩種
1. 增加filename到search cond裡
2. 可以從[]byte article取，但在這層做byte manipulation好像不太好(?)
不確定哪個比較好?

2021-08-16 04:40 UTC, PichuChen commented on internal/usecase/article.go
> +		Title: filename,
在使用者一般的介面中是沒有 filename 的概念的，在 Web 出現之前有的是 AID ，中文叫文章 ID ，那個是由 filename 計算出來的一個對應編碼文字。

在Web 出現之後網址會有的數字就是 filename ，原則上是以 timestamp 和亂數組成（大多數BBS系統皆以此方式進行）

因此不太需要針對 timestamp 進行搜尋（除非說要透過 filename 搜尋發文時間，但是不建議）

不過這個需求為什麼會需要用到搜尋？

2021-08-16 04:56 UTC, kyho4515 commented on internal/usecase/article.go
> +		Title: filename,
了解，我想的可能比較偏向要有個函式從filename得到file header (bbs.ArticleRecord)，因為這樣我可以直接call owner()
目前我能找到的就只有從filename得到[]byte形式的整段article
而我覺得在這層從[]byte形式的整段article分析他的header有點違背原本的設計

2021-08-16 05:12 UTC, PichuChen commented on internal/usecase/article.go
> +		Title: filename,
這樣的函式有，但是不會叫他Search

不過認真來說其實現階段 open file header 之後 O(n) 去掃描某個看板內的所有文章我認為是可以接受的

2021-08-16 05:13 UTC, PichuChen commented on internal/usecase/article.go
> +		Title: filename,
https://pkg.go.dev/github.com/Ptt-official-app/go-bbs#DB.ReadBoardArticleRecordsFile

不知道這個有沒有符合要求？

2021-08-16 05:46 UTC, kyho4515 commented on internal/usecase/article.go
> +		Title: filename,
這會回傳整個board的[]bbs.ArticleRecord，所以也還是要用filename去找是哪個
如果這樣ok的話，我這兩天就用改search cond的方式去找？

另外好奇問一下，我看go-bbs裏，似乎這些file header(bbs.ArticleRecord)是以一個board為單位跟原本的articles分開存在另一個檔案裡的？

2021-08-16 05:54 UTC, PichuChen commented on internal/usecase/article.go
> +		Title: filename,
> 如果這樣ok的話，我這兩天就用改search cond的方式去找？
OK，另外如果你覺得時間複雜度上不妥的話，可以加一個 TODO
另外其實目前 PTT 的 C 程式標題搜尋也是 O(n) 只是它會做快取暫存，所以如果是很冷門的關鍵字在大型版，例如 `}` 那會在第一次搜尋的時候明顯感覺到鈍感，但是第二次就消失了。

> 另外好奇問一下，我看go-bbs裏，似乎這些file header(bbs.ArticleRecord)是以一個board為單位跟原本的articles分開存在另一個檔案裡的？

是的，實作細節可以參考 go-bbs 或是 pttbbs 的 c 程式碼， BBS 會在每個版面用一個資料夾來儲存，每個資料夾會有個 `.DIR` 的檔案作為文章索引， `.DIR` 記載諸如文章作者、標題、filename等等的資訊，filename 下的檔案則是完整的文章內文。

2021-08-27 15:29 UTC, nickyanggg commented on internal/usecase/article.go
> +	} else {
else block 的內容可能就直接拉出來？另外對於 usecase 的部分有辦法加簡單的 test 嗎

2021-08-27 16:42 UTC, kyho4515 commented on internal/usecase/article.go
> +	} else {
ok. 之前在等repo的function, test晚點補

2021-08-31 07:31 UTC, kyho4515 commented
test function我不確定怎麼寫比較好, 如果有什麼建議都可以提出來

2021-09-01 02:16 UTC, y2468101216 commented
LGTM

2021-09-01 02:18 UTC, y2468101216 commented on internal/usecase/article.go
> +		return nil, fmt.Errorf("Cannot push this time")
這邊改成你已經 push 過了會比較好

2021-09-01 03:45 UTC, kyho4515 commented on internal/usecase/article.go
> +		return nil, fmt.Errorf("Cannot push this time")
Updated!

2021-09-03 00:34 UTC, nickyanggg requested changes

2021-09-03 00:34 UTC, nickyanggg commented on internal/usecase/article.go
> +	p, err := usecase.repo.AppendComment(ctx, userID, boardID, filename, appendType, "")
這邊應該可以直接回傳 `return usecase.xxx`？而不用再做下面的判斷，加了下面感覺會有點多此一舉

2021-09-03 00:42 UTC, kyho4515 commented on internal/usecase/article.go
> +	p, err := usecase.repo.AppendComment(ctx, userID, boardID, filename, appendType, "")
這邊不做error check?

2021-09-03 01:00 UTC, nickyanggg commented on internal/usecase/article.go
> +	p, err := usecase.repo.AppendComment(ctx, userID, boardID, filename, appendType, "")
因為回傳內容即 PushRecord、error，所以你下面加的 error check 後再回傳其實就好像只是覆寫掉 usecase.xxx 回傳的 error 內容而已

2021-09-03 01:07 UTC, kyho4515 commented on internal/usecase/article.go
> +	p, err := usecase.repo.AppendComment(ctx, userID, boardID, filename, appendType, "")
我的想法是這邊把err多包一層加上目前這個function的敘述, 在發生error的情況, 可以從err的訊息trace每一層的function call.
如果不檢查的話, 就沒辦法加上目前這個function的敘述了

2021-09-03 01:31 UTC, nickyanggg commented on internal/usecase/article.go
> +	p, err := usecase.repo.AppendComment(ctx, userID, boardID, filename, appendType, "")
但感覺覆蓋掉就會直接無法知道 error 從哪來的樣子耶，像是假如 usecase.xxx 裡面有三個檢查 error 的地方並且回傳 error 的資訊分別為 1、2、3，那這邊覆蓋掉的話，我們就會不知道 error 是從三個中的哪一個出錯

2021-09-03 01:58 UTC, nickyanggg commented
另外想問一下，目前的實作方式是不是無法避免其他使用者的刻意留言？也就是說假如有人的留言帶有其他使者的名字以及推噓文符號，是不是那位被提到的使用者在推噓文的時候就會計算到別人的刻意留言？

2021-09-03 04:29 UTC, kyho4515 commented
> 另外想問一下，目前的實作方式是不是無法避免其他使用者的刻意留言？也就是說假如有人的留言帶有其他使者的名字以及推噓文符號，是不是那位被提到的使用者在推噓文的時候就會計算到別人的刻意留言？

目前看起來是這樣, 如果多加個檢查上下箭頭前一個rune是否為 `\n` 不知道能不能處理這個問題？

2021-09-03 05:46 UTC, y2468101216 commented
> > 另外想問一下，目前的實作方式是不是無法避免其他使用者的刻意留言？也就是說假如有人的留言帶有其他使者的名字以及推噓文符號，是不是那位被提到的使用者在推噓文的時候就會計算到別人的刻意留言？
> 
> 目前看起來是這樣, 如果多加個檢查上下箭頭前一個rune是否為 `\n` 不知道能不能處理這個問題？

我個人認為依照 ptt 現行做法怎樣都會被有心人操弄，因為畢竟寫入推文的時候我們不會刻意去檢查推文是否有含上下箭頭
多+ /n 也只是避免一般使用者誤碰而已

2021-09-04 02:10 UTC, kyho4515 commented
> > > 另外想問一下，目前的實作方式是不是無法避免其他使用者的刻意留言？也就是說假如有人的留言帶有其他使者的名字以及推噓文符號，是不是那位被提到的使用者在推噓文的時候就會計算到別人的刻意留言？
> > 
> > 
> > 目前看起來是這樣, 如果多加個檢查上下箭頭前一個rune是否為 `\n` 不知道能不能處理這個問題？
> 
> 我個人認為依照 ptt 現行做法怎樣都會被有心人操弄，因為畢竟寫入推文的時候我們不會刻意去檢查推文是否有含上下箭頭
> 多 + ` \n` 也只是避免一般使用者誤碰而已，不過我覺得這個想法很好，能避免一般使用者誤觸就夠了，剩下的靠版主處理

我想的是在寫入的時候, `\n`(換行)之後加個`→`之類的做區別, 所以推文時就是`\n↑`, 使用者使用換行的話就是`\n→`
我以為平常在ppt上看到的換行看起來就像換行後有個右箭頭?

2021-09-10 06:47 UTC, PichuChen approved these changes
LGTM

2021-09-10 06:47 UTC, merged