implement recommend_count_gt and recommend_count_lt in articles
Ptt-official-app/Ptt-backend pull request #290
Opened 2021-09-18 07:44 UTC by karta0807913

* remove unused fields `RecommendCountLessThan` and `RecommendCountGreaterThan`

## 👏 解決掉的 issue / Resolved Issues
- close #279 

## ⛏ 變更內容 / Details of Changes

- 在 `/v1/boards/{{board_id}}/articles` 加入 `recommend_count_gt` 與 `recommend_count_lt` 選項
- 新增 `delivery.getBoardArticles` 函數的自動測試

2021-09-18 08:02 UTC, y2468101216 requested changes

2021-09-18 08:02 UTC, y2468101216 commented on internal/delivery/http/route_boards_articles.go
> +	}
不要用匿名函數，除非你是要 callback 可以在 repository 或者直接在 controller 下定義一個新的方法

2021-09-18 08:02 UTC, y2468101216 commented on internal/delivery/http/route_boards_articles.go
> +		return
要回傳錯誤訊息

2021-09-18 10:18 UTC, karta0807913 commented on internal/delivery/http/route_boards_articles.go
> +		return
@y2468101216 已修正

2021-09-18 10:20 UTC, karta0807913 commented on internal/delivery/http/route_boards_articles.go
> +	}
@y2468101216 這個函數是拿來隱藏下面重複的code的，我覺得這樣會讓這整個 function 看起來比較乾淨
當然如果希望我展開的話也是可以的

2021-09-22 01:29 UTC, y2468101216 commented on internal/delivery/http/route_boards_articles.go
> +	}
就在 controller 底下定義這個 func 吧

2021-09-22 01:29 UTC, y2468101216 commented
@PichuChen @nickyanggg 請幫忙 review

2021-09-22 02:36 UTC, nickyanggg approved these changes
邏輯上看起來沒啥問題

2021-09-23 10:07 UTC, y2468101216 commented
LGTM

2021-09-23 10:10 UTC, PichuChen requested changes

2021-09-23 10:10 UTC, PichuChen commented on internal/delivery/http/route_boards_articles_test.go
> +	UseCase "github.com/Ptt-official-app/Ptt-backend/internal/usecase"
這邊建議使用 `usecase`

2021-09-23 10:12 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +	getRecommendCount := func(name string) (*int, error) {
Golang 慣例上並不會會傳 *int 建議回傳 int 然後用 error 是否為 nil 來判斷是否有錯誤。

2021-09-23 10:14 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +			return nil, nil
這時候可以回應 return 0, fmt.Errorf("no input") 這樣，那就知道這邊沒有要限制了

2021-09-23 10:14 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +		w.WriteHeader(http.StatusBadRequest)
這邊不一定一定要回傳Bad Request, 可以視錯誤狀況決定回傳，也有可能忽略掉該參數

2021-10-02 08:13 UTC, karta0807913 commented
因為之前的寫法（使用匿名函數）似乎可讀性較差，所以將其整個重寫成可復用的結構（URLValuesParser）
還請各位幫我看看這樣是不是更好閱讀了

2021-10-02 08:27 UTC, y2468101216 commented
usecase 的地方要改，然後我看重寫的部份沒啥問題

2021-10-02 08:43 UTC, karta0807913 commented
> usecase 的地方要改，然後我看重寫的部份沒啥問題

已修正

2021-10-13 03:38 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +	recommendCountGreaterEqual, recommendCountGreaterEqualIsSet := parser.GetGreaterEqual()
在 Golang 的寫法中印象在比較小的區域的區域變數可以讓變數名稱短一點沒關係，像是 `recGECnt` 這樣的東西或者是 `GECnt` 這樣的東西應該是可以被接受的，不過全部寫出來好像也不能算錯就是。

2021-10-13 03:43 UTC, PichuChen approved these changes
LGTM

2021-10-13 03:43 UTC, merged