fix article-forward router
Ptt-official-app/Ptt-backend pull request #292
Opened 2021-09-20 09:39 UTC by karta0807913

## 👏 解決掉的 issue / Resolved Issues
- close #286 

## ⛏ 變更內容 / Details of Changes

* change parameter `board` to `board_id` ([文件](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.r3t24bsqupvy)裡面是寫 `board_id` 而非 `board`)
* add permission type `PermissionForwardArticleToBoard` and `PermissionForwardArticleToEmail`
* remove permission type `PermissionForwardArticle` and `PermissionForwardAddArticle`
* fix test file `C6-1-7.sh` and `C6-1-8.sh` in testing-script
* remove redundant test in function `usecase.ForwardArticleToBoard` (我看其他的函數都沒有檢查，只有這個有，所以我就統一都刪掉了)
* add error `NoPermissionForForwardArticleError` and `NoPermissionForForwardArticleToEmailError`

2021-09-20 12:22 UTC, PichuChen commented on internal/delivery/http/route_forward_article.go
> +			"to_board":   toBoard,
這邊的參數名稱感覺需要文件化

2021-09-20 12:23 UTC, PichuChen commented on internal/delivery/http/route_forward_article_test.go
> +	UseCase "github.com/Ptt-official-app/Ptt-backend/internal/usecase"
應該不需要特別改成 `UseCase` 用 `usecase` 就行了。

2021-09-20 12:24 UTC, PichuChen commented on internal/usecase/token.go
> +func (usecase *usecase) checkForwardArticleToBoardPermission(token string, userInfo map[string]string) error {
需要增加判斷用參數的註解

2021-09-20 12:25 UTC, PichuChen requested changes
有些函式的註解需要補充

2021-10-02 05:56 UTC, karta0807913 commented on internal/delivery/http/route_forward_article.go
> +			"to_board":   toBoard,
這邊的話我看大家都是這麼放的
https://github.com/Ptt-official-app/Ptt-backend/blob/5067b7e65b29d9a22d83a7df5ebe54768e58380b/internal/delivery/http/route_append_comment.go#L38-L43

https://github.com/Ptt-official-app/Ptt-backend/blob/5067b7e65b29d9a22d83a7df5ebe54768e58380b/internal/usecase/token.go#L125-L134

如果需要文件化的話請問要放在哪裡呢？

2021-10-02 05:58 UTC, karta0807913 commented on internal/delivery/http/route_forward_article_test.go
> +	UseCase "github.com/Ptt-official-app/Ptt-backend/internal/usecase"
這邊的話是因為如果使用 `usecase` 的話會與區域變數的 `usecase` 衝突

https://github.com/Ptt-official-app/Ptt-backend/blob/5067b7e65b29d9a22d83a7df5ebe54768e58380b/internal/delivery/http/route_forward_article_test.go#L118-L135

還是請問有更好的名稱建議？

2021-10-02 05:59 UTC, karta0807913 commented on internal/usecase/token.go
> +func (usecase *usecase) checkForwardArticleToBoardPermission(token string, userInfo map[string]string) error {
不好意思我看不懂這是什麼意思QQ

2021-10-02 08:00 UTC, PichuChen commented on internal/usecase/token.go
> +func (usecase *usecase) checkForwardArticleToBoardPermission(token string, userInfo map[string]string) error {
通常 Golang 的註解有些會放在函式上面
https://cs.opensource.google/go/go/+/refs/tags/go1.17.1:src/net/http/request.go;drc=e6dda19888180c5159460486d30c0412e4980748;l=1431


![截圖 2021-10-02 下午3 59 37](https://user-images.githubusercontent.com/600238/135708553-f9919b62-cac6-4c2c-a634-27d398a63794.png)
像是這樣。

這樣的話 Review 的時候就能幫忙看行為和註解一不一樣，然後使用時也可以不用真的進去看也可以知道行為。

2021-10-02 08:28 UTC, karta0807913 commented on internal/usecase/token.go
> +func (usecase *usecase) checkForwardArticleToBoardPermission(token string, userInfo map[string]string) error {
已加入

2021-10-02 08:41 UTC, y2468101216 commented on internal/delivery/http/route_forward_article_test.go
> +	UseCase "github.com/Ptt-official-app/Ptt-backend/internal/usecase"
permission 的部份應該不需要被 mock ?

2021-10-02 08:47 UTC, karta0807913 commented on internal/delivery/http/route_forward_article_test.go
> +	UseCase "github.com/Ptt-official-app/Ptt-backend/internal/usecase"
> permission 的部份應該不需要被 mock ?

這個函數是在確認到底請求時有沒有呼叫過 permission check

2021-10-02 08:48 UTC, karta0807913 commented on internal/delivery/http/route_forward_article_test.go
> +	UseCase "github.com/Ptt-official-app/Ptt-backend/internal/usecase"
已將變數名稱重新命名
usecase -> mockUsecase
UseCase -> usecase

2021-10-13 03:47 UTC, PichuChen commented on internal/delivery/http/route_forward_article.go
> +			"to_board":   toBoard,
在 `checkAppendCommentPermission` 的前面

2021-10-13 03:48 UTC, PichuChen approved these changes
LGTM

2021-10-13 03:48 UTC, merged