add post token test and add .vscode gitignore
Ptt-official-app/Ptt-backend pull request #37
Opened 2021-02-05 03:44 UTC by y2468101216

## 📝 相關的 issue / Related Issues
- #36 

## ⛏ 變更內容 / Details of Changes
- 增加 route_token_test.go
- 增加 gitignore .vscode

先不要合，我只是先發上來看看大家覺得這樣寫法是否可以
然後 git ignore .vscode 我覺得可以先增加了，因為沒買 goland 的不是 vscode 就是 sublime 3

2021-02-05 17:22 UTC, mkfsn commented on route_token_test.go
> +package main
想請教一下，這個檔案是有討論過要放在哪邊嗎？因為是 package main 然後是 Test 讓我有點困惑。

2021-02-05 18:23 UTC, teyuchang commented
Could you please rebase onto the latest `development` branch?
We have changed the project layout in this PR https://github.com/Ptt-official-app/Ptt-backend/pull/23

2021-02-05 18:39 UTC, sageofcross commented on route_token_test.go
> +package main
依照 Go 的慣例，測試檔案通常與被測試檔案放在一起，唯一區別是文件是否跟著 `_test` 後綴。

而 `package` 的命名你會看見兩種，這邊以 `fmt` 當例子：

- fmt
- fmt_test

其中的差別在於前者因為處於同一個 `package` 所以可以使用 unexported func ；後者則是視為不同套件所以只能測試 exported func ，也就是白相與黑箱測試。

為了統一建議使用黑箱（也就是 `fmt_test` ）來當測試的套件名，正常情況下其實不該測 Private 的函式。

2021-02-06 03:20 UTC, y2468101216 commented on route_token_test.go
> +package main
這樣的話我要順便把原有的 route_user_test.go改掉嗎

2021-02-06 03:20 UTC, y2468101216 commented
> Could you please rebase onto the latest `development` branch?
> We have changed the project layout in this PR #23

ok，I will rebase on Monday.

2021-02-08 08:11 UTC, y2468101216 commented
> Could you please rebase onto the latest `development` branch?
> We have changed the project layout in this PR #23

reabse done.  if I need to squash, please tell me

2021-02-09 15:58 UTC, PichuChen requested changes

2021-02-09 15:58 UTC, PichuChen commented on internal/delivery/http/route_users_test.go
> +	"time"
為什麼要另外把 "time" package 移動到上面兩行？

2021-02-09 15:58 UTC, PichuChen commented on internal/mock/user_record.go
> +package mock
mock package 應該要被拿掉了

2021-02-17 06:48 UTC, PichuChen approved these changes

2021-02-17 06:49 UTC, PichuChen commented
LGTM

2021-02-18 03:00 UTC, closed without merging