Implement #53 Get popular board list
Ptt-official-app/Ptt-backend pull request #54
Opened 2021-02-11 14:34 UTC by nickyanggg

## 📝 相關的 issue / Related Issues
- 主 issue #51 
- 實作 issue #53

## ⛏ 變更內容 / Details of Changes

- 實作 delivery/http/route_boards.go 中的 getPopularBoardList
- 實作 usecase/board.go 中的 GetPopularBoards
- TODO: 依 BoardRecord 中的 number_of_user 遞減排序

2021-02-12 06:50 UTC, PichuChen approved these changes
LGTM

2021-02-13 14:13 UTC, PHChenGit approved these changes

2021-02-13 14:13 UTC, PHChenGit commented
LGTM

2021-02-13 15:07 UTC, PichuChen requested changes

2021-02-13 15:07 UTC, PichuChen commented on internal/delivery/http/route_users_test.go
> +	panic("Not implemented")
這邊能不能不要用 panic, 而是return error?

2021-02-13 15:07 UTC, PichuChen commented on internal/usecase/usecase.go
> +	GetPopularBoards(ctx context.Context) []bbs.BoardRecord
回傳的部分建議增加 error

2021-02-13 18:36 UTC, nickyanggg commented on internal/delivery/http/route_users_test.go
> +	panic("Not implemented")
好，待會改

2021-02-13 18:36 UTC, nickyanggg commented on internal/usecase/usecase.go
> +	GetPopularBoards(ctx context.Context) []bbs.BoardRecord
好～

2021-02-13 18:50 UTC, nickyanggg commented
已修改完畢，那因為目前 GetPopularBoards 太過簡單，所以目前 error 值都回傳 nil，之後如果排序的部分可以實作或是 usecase.repo.GetBoards 也有回傳 error 值的話再更改。

2021-02-13 19:23 UTC, PichuChen approved these changes
LGTM

2021-02-18 14:16 UTC, closed without merging