add route classes test
Ptt-official-app/Ptt-backend pull request #57
Opened 2021-02-12 14:20 UTC by TimoChiang

## 👏 解決掉的 issue / Resolved Issues
- close #47

## 📝 相關的 issue / Related Issues
- #36

## ⛏ 變更內容 / Details of Changes

- 新增route_classes_test.go，增加getClassesList的測試
- 新增route_classes_mock_test.go，把測試classes用到的mock移至此檔案

2021-02-12 14:55 UTC, PichuChen approved these changes
LGTM

2021-02-14 21:10 UTC, Julian-Chu requested changes

2021-02-14 21:10 UTC, Julian-Chu commented on internal/delivery/http/route_classes_test.go
> +
多餘的空行

2021-02-14 21:10 UTC, Julian-Chu commented on internal/delivery/http/route_classes_test.go
> +	responsedSlice := responsedMap["data"]
responseData或是data比Slice更符合資料欄位

2021-02-14 21:10 UTC, Julian-Chu commented on internal/delivery/http/route_classes_test.go
> +	responsedMap := map[string][]interface{}{}
typo -> responseMap
下幾行的responsedXXX 也是

2021-02-14 21:10 UTC, Julian-Chu commented on internal/delivery/http/route_classes_test.go
> +		responsedData := d.(map[string]interface{})
這邊應該是回傳看板資料，board會比responseData好

2021-02-14 21:10 UTC, Julian-Chu commented on internal/delivery/http/route_classes_mock_test.go
> +	boardId string
目前變數名稱的ID會採用`ID` 而非`Id`
請見 https://github.com/Ptt-official-app/Ptt-backend/issues/38#issuecomment-776222480

ps:  方法的ID大小寫，暫時不用處理，等後續interface更動在改即可

2021-02-15 15:01 UTC, Julian-Chu approved these changes
LGTM

2021-02-17 03:01 UTC, y2468101216 commented
LGTM

2021-02-17 06:00 UTC, merged