Implement issue #58 [主線] [PTT] 實作個人看板的使用者資訊 (repository)
Ptt-official-app/Ptt-backend pull request #69
Opened 2021-02-13 16:35 UTC by gn01842919

## 👏 解決掉的 issue / Resolved Issues
- close #58

## 📝 相關的 issue / Related Issues
- #主 issue #52
- #子 issue #58

## ⛏ 變更內容 / Details of Changes
- 新增 interface `BBSUserRecord `，用來在 `bbs.UserRecord` 外面包一層 go-bbs 尚未支援的方法，並同步調整 test 相關的 mock，包含:
    - NumBadPosts() int
    - LastCountry() string
    - MailboxDescription() string
    - ChessStatus() map[string]interface{}
    - Plan() map[string]interface{}
- 實作 `getMoneyDiscription()` 以顯示經濟狀況

2021-02-13 19:21 UTC, PichuChen requested changes

2021-02-13 19:21 UTC, PichuChen commented on internal/repository/repository.go
> +	GetUsers(ctx context.Context) []BBSUserRecord
這邊應該還是要保留 bbs.UserRecord, 另外要多回傳 error

2021-02-13 19:21 UTC, PichuChen commented on internal/repository/repository.go
> +	userRecords  []BBSUserRecord
這邊應該還是要保留回傳 bbs.UserRecord

2021-02-15 02:58 UTC, gn01842919 commented on internal/repository/repository.go
> +	GetUsers(ctx context.Context) []BBSUserRecord
Fixed in commit https://github.com/Ptt-official-app/Ptt-backend/pull/69/commits/c07927e7098448d5fcddb2676e5264766b0088cd

2021-02-15 02:58 UTC, gn01842919 commented on internal/repository/repository.go
> +	userRecords  []BBSUserRecord
Fixed.

2021-02-15 05:55 UTC, PichuChen approved these changes
LGTM

2021-02-15 19:30 UTC, Julian-Chu requested changes

2021-02-15 19:30 UTC, Julian-Chu commented on internal/repository/user.go
> +	results := make([] bbs.UserRecord, len(userRecords))
make([] bbs.UserRecord, 0, len(userRecords))
或是下面的迴圈內改用index assign
目前的寫法會導致results有多餘的nil

2021-02-16 16:22 UTC, gn01842919 commented on internal/repository/user.go
> +	results := make([] bbs.UserRecord, len(userRecords))
Fixed. Thanks.

2021-02-16 17:14 UTC, Julian-Chu approved these changes
LGTM

2021-02-16 17:16 UTC, merged