Test: Route get boards list
Ptt-official-app/Ptt-backend pull request #70
Opened 2021-02-14 11:40 UTC by PHChenGit

## 👏 解決掉的 issue / Resolved Issues
- close #55 
- close #0

## 📝 相關的 issue / Related Issues
- #55 

## ⛏ 變更內容 / Details of Changes

- Add route boards tests

2021-02-15 13:01 UTC, PichuChen requested changes

2021-02-15 13:01 UTC, PichuChen commented on internal/delivery/http/route_boards_mock_test.go
> +func (b *MockBoardRecord) BoardId() string { return b.boardID }
可以先另外實作一個 BoardID() string {return b.BoardId} 或是反過來，因為接下來 go-bbs 那邊應該也會把 BoardId 變成 BoardID

2021-02-15 13:01 UTC, PichuChen commented on internal/delivery/http/route_boards_mock_test.go
> +func (b *MockBoardRecord) ClassId() string { return "" }
同上 BoardId

2021-02-15 14:21 UTC, PHChenGit commented on internal/delivery/http/route_boards_mock_test.go
> +func (b *MockBoardRecord) BoardId() string { return b.boardID }
我理解一下
意思是說先實作下面這個函式
`func (b *MockBoardRecord) BoardID string { return b.BoardID }`
等到 go-bbs 也改成 BoardID 之後再把 Ptt-backend 的 BoardId 刪掉嗎？

2021-02-15 14:22 UTC, PichuChen commented on internal/delivery/http/route_boards_mock_test.go
> +func (b *MockBoardRecord) BoardId() string { return b.boardID }
對

2021-02-15 14:22 UTC, PichuChen commented on internal/delivery/http/route_boards_mock_test.go
> +func (b *MockBoardRecord) BoardId() string { return b.boardID }
然後原有的 boardId 為了保持相容可以先 return b.BoardId() 這樣

2021-02-16 00:08 UTC, Julian-Chu commented on internal/delivery/http/route_boards_test.go
> +}
兩個測試還缺對response欄位的驗證 參照 #57

2021-02-17 06:39 UTC, y2468101216 commented
請改為對 development_enable_lint 送 pr 歐

2021-02-17 14:00 UTC, PHChenGit commented
> 請改為對 development_enable_lint 送 pr 歐

Changed.

2021-02-17 15:56 UTC, PichuChen commented on internal/delivery/http/route_boards_articles.go
> +		RecommendCountLessEqualIsSet:    recommendCountLessEqualIsSet,
問一下為什麼明明是增加 Test 的ISSUE 但是好像新增了不少是功能面的程式碼？

2021-02-17 15:57 UTC, PichuChen commented on internal/delivery/http/route_boards_articles_test.go
> +	recommendCountGe := "qwerty"
```suggestion
	recommendCountGreaterEqual := "qwerty"
```

建議在縮寫的部分是改成 GE 或者是 GreaterEqual

2021-02-17 15:57 UTC, PichuChen commented on internal/delivery/http/route_boards_articles_test.go
> +	v.Set("recommend_count_ge", recommendCountGe)
```suggestion
	v.Set("recommend_count_ge", recommendCountGreaterEqual)
```

2021-02-17 16:01 UTC, PichuChen requested changes
有些 struct 放置於哪個檔案的修改並沒有在 ISSUE 當中被提及，這樣不知道合併進去之後其他人在同步進行用到這些 struct 時會不會造成混亂？

2021-02-17 16:15 UTC, PHChenGit commented on internal/delivery/http/route_boards_articles.go
> +		RecommendCountLessEqualIsSet:    recommendCountLessEqualIsSet,
應該是我更新 Branch 時都是從 development 拉下來的關係....
不確定 developement & development_enable_lint 這兩隻 branch 有沒有同步就是....

2021-02-17 16:15 UTC, PHChenGit commented on internal/delivery/http/route_boards_articles_test.go
> +	recommendCountGe := "qwerty"
這部分的 code 是我拉 development 下來的部分
不在這次修改範圍

2021-02-17 16:16 UTC, PHChenGit commented on internal/delivery/http/route_boards_articles_test.go
> +	v.Set("recommend_count_ge", recommendCountGe)
同上

2021-02-17 16:20 UTC, PHChenGit commented
Target branch 改成 development_enable_lint 之後多了一些問題

1. development & development_enable_lint 似乎 code 沒有同步 所以我的 branch 拉 development 下來更新後產生很多新的檔案 但不是這次修改範圍的
2. 有一些原本的檔案 lint 失敗 例如：
   - internal/delivery/http/route.go:24:31: func `(*httpDelivery).routeClass` is unused (unused)
   - internal/delivery/http/route_classes.go:14:31: func `(*httpDelivery).getClass` is unused (unused)
   - internal/delivery/http/route_users_mock_test.go:25:6: type `MockUserRecord` is unused (unused)

2021-02-19 05:10 UTC, PichuChen commented
> Target branch 改成 development_enable_lint 之後多了一些問題
> 
> 1. development & development_enable_lint 似乎 code 沒有同步 所以我的 branch 拉 development 下來更新後產生很多新的檔案 但不是這次修改範圍的

那這樣可能要調整改成用 development_enable_lint 做修改？

> 2. 有一些原本的檔案 lint 失敗 例如：
>    
>    * internal/delivery/http/route.go:24:31: func `(*httpDelivery).routeClass` is unused (unused)
>    * internal/delivery/http/route_classes.go:14:31: func `(*httpDelivery).getClass` is unused (unused)
>    * internal/delivery/http/route_users_mock_test.go:25:6: type `MockUserRecord` is unused (unused)

目前有些 lint 失敗是還 OK 的，因為本來他就 lint 失敗了。

2021-02-22 02:11 UTC, y2468101216 commented
請改為 base on development_enable_lint 開發

2021-02-22 16:13 UTC, PHChenGit commented
In order to follow testing branch style, so switch to new branch and open another branch.

2021-02-22 16:13 UTC, closed without merging