usecase for get popular articles
Ptt-official-app/Ptt-backend pull request #85
Opened 2021-02-21 02:10 UTC by wagaru

## 👏 解決掉的 issue / Resolved Issues
- close #83 

## 📝 相關的 issue / Related Issues
- 支線 #83 
- 主線 #50 

## ⛏ 變更內容 / Details of Changes

- usecase 新增 article.go, 實作 GetPopularArticles()
- usecase 新增 article_test.go & article_mock_test.go 以測試 usecase.GetPopularArticles()
- repository 新增 article.go，定義 GetPopularArticles()，沒有實作內容

目前相關邏輯是單獨拉到 article.go，並沒有放在 board.go。
主要是覺得可以跟 board 脫鉤，但如果大家覺得沒必要的話可以再移回 board.go

2021-02-21 10:13 UTC, gn01842919 commented
我看文件中 Popular Article 看起來比 Article 多了一個 board_id 欄位，也許 go-bbs 應該有要個 PopularArticleRecord 的 interface 才對? @PichuChen 是這樣嗎，還是我誤解了呢?

2021-02-21 10:19 UTC, PichuChen commented
有可能是go-bbs沒有開到欄位，如果是的話可能要在go-bbs那邊開ISSUE

2021-02-23 21:00 UTC, Julian-Chu requested changes

2021-02-23 21:00 UTC, Julian-Chu commented on internal/usecase/article_test.go
> +	resp := &MockRepository{}
typo:   should be repo

2021-02-24 04:41 UTC, PichuChen commented on internal/repository/article.go
> +	return []bbs.ArticleRecord{}, nil
```suggestion
        // TODO: should implement popular articles there 
	return []bbs.ArticleRecord{}, nil
```

這邊的程式碼看起來是 Mocking 應該要加上 TODO 讓其他人知道這邊不應該固定回傳空 Slice 。

2021-02-24 04:44 UTC, PichuChen commented on internal/usecase/article.go
> +func (usecase *usecase) GetPopularArticles(ctx context.Context) ([]bbs.ArticleRecord, error) {
```suggestion
// GetPopularArticles returns ... .... by .... ... 
func (usecase *usecase) GetPopularArticles(ctx context.Context) ([]bbs.ArticleRecord, error) {
```

需要補上註解說明目前usecase 是按照什麼回應人氣文章的，已讀數量？推文數量？

根據 PTT APP 那邊開發會議目前的大方向應該會以「留言數量」(推+噓+箭頭) 作為人氣文章的排序依序

不過目前沒有這項資訊的話，應該也可以寫TBD或是另外開ISSUE討論

2021-02-24 05:59 UTC, wagaru commented on internal/usecase/article_test.go
> +	resp := &MockRepository{}
fixed, thanks~

2021-02-24 05:59 UTC, wagaru commented on internal/repository/article.go
> +	return []bbs.ArticleRecord{}, nil
fixed, thanks~

2021-02-24 06:01 UTC, wagaru commented on internal/usecase/article.go
> +func (usecase *usecase) GetPopularArticles(ctx context.Context) ([]bbs.ArticleRecord, error) {
我看文件上有 `comment count` 說明是留言數量，不分推噓文，我先假設是照這欄排序好了
然後資料是否要 top N 之後再開 issue 討論嗎？

2021-02-24 06:07 UTC, PichuChen commented on internal/usecase/article.go
> +func (usecase *usecase) GetPopularArticles(ctx context.Context) ([]bbs.ArticleRecord, error) {
如何排序可以回應或者是開ISSUE都可以，這邊Review上面只是針對沒有註解的這件事提出意見而已。

2021-02-24 07:29 UTC, Julian-Chu approved these changes
LGTM

2021-02-28 06:37 UTC, merged