Add mock for repository.GetPopularArticleRecords
Ptt-official-app/Ptt-backend pull request #87
Opened 2021-02-21 10:51 UTC by gn01842919

and repository.BBSPopularArticleRecord

since go-bbs has not implemented it yet

## 👏 解決掉的 issue / Resolved Issues
- close https://github.com/Ptt-official-app/Ptt-backend/issues/86

## 📝 相關的 issue / Related Issues
- https://github.com/Ptt-official-app/Ptt-backend/issues/50

## ⛏ 變更內容 / Details of Changes
- add `BBSPopularArticleRecord` to mock `bbs.PopularArticleRecord` since go-bbs has not implemented it yet
- add `GetPopularArticles()` to interface `Repository`

2021-02-21 18:54 UTC, PichuChen requested changes

2021-02-21 18:54 UTC, PichuChen commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
這個函式的其他函式好像都在 usecase/board_mock_test.go 
![截圖 2021-02-22 上午2 47 08](https://user-images.githubusercontent.com/600238/108635093-42e46180-74b8-11eb-8f4a-0aacae91bdfb.png)

有考慮放在一起嗎？

2021-02-21 18:54 UTC, PichuChen commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
前面應該可以不用前綴 BBS?

2021-02-21 18:54 UTC, PichuChen commented on internal/repository/article.go
> +//BBSPopularArticleRecord : Mock of bbs.PopularArticleRecord
這邊應該不是 Mock 了， 
// PopularArticleRecord is an ArticleRecord which has boardID information.

這樣會不會比較好？ 另外我不確定熱門文章在 go-bbs 回傳會不會回傳整個原有 ArticleRecord 的所有資訊（像是 Money 之類的） 因此會不會把 ArticleRecord 拆開之後放進必要的元素進來會比較好？

2021-02-21 18:54 UTC, PichuChen commented on internal/repository/article.go
> +	BoardId() string
BoardId 接下來會改成 BoardID 喔

2021-02-22 10:56 UTC, gn01842919 commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
我是依照 @wagaru 的 PR https://github.com/Ptt-official-app/Ptt-backend/pull/85/files
來放的，放哪裡我是都無所謂
只有這個建議放到 board 那邊嗎? 因為 article .go 裡面應該也是一樣的邏輯，看是要統一拉出來還是統一放回到 board 那邊

2021-02-22 10:58 UTC, gn01842919 commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
我上次 mock UserRecord 的 PR 的 naming 是有 BBS 的: https://github.com/Ptt-official-app/Ptt-backend/pull/69/files

需要統一嗎?

2021-02-22 10:59 UTC, gn01842919 commented on internal/repository/article.go
> +//BBSPopularArticleRecord : Mock of bbs.PopularArticleRecord
OK

2021-02-22 10:59 UTC, gn01842919 commented on internal/repository/article.go
> +	BoardId() string
OK

2021-02-22 10:59 UTC, PichuChen commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
我覺得可以統一放到 MockRepository 在的檔案，比較不會找到亂掉

2021-02-22 11:00 UTC, PichuChen commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
先前應該是為了因為缺少一些 Method 所以暫時開的？

2021-02-22 13:42 UTC, gn01842919 commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
對

2021-02-22 13:48 UTC, gn01842919 commented on internal/repository/article.go
> +//BBSPopularArticleRecord : Mock of bbs.PopularArticleRecord
[PTT 後端系統協定](https://docs.google.com/document/d/18DsZOyrlr5BIl2kKxZH7P2QxFLG02xL2SO0PzVHVY3k/edit#heading=h.1ehnllv3ris) 裡面，`GET /v1/pupular-articles` 的回傳格式裡有 "money"，所以這邊也可能會改囉?

那有大概知道那些欄位會是必要的嗎?

2021-02-23 01:18 UTC, wagaru commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
想問一下如果這邊要改到 board_mock_test.go 裡的話，我那邊的 PR 也需要改嗎？

另外覺得當初其實不用分 usecase / repository 給二個人寫，畢竟都算簡單。
如果都同一個人寫的話其實問題比較少，不然目前分成二個 PR，但裡面 function 的實作都不一樣，最後 merge 回 development 時應該還要再解一次

2021-02-23 03:17 UTC, PichuChen commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
@wagaru  哪個 PR 有編號嗎？

然後目前作法是切開成三個 Package，理論上應該是比較晚 Merge 的那個要再把他整個串起來

2021-02-23 03:17 UTC, PichuChen commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
但是這個應該沒有少 Method?

2021-02-23 03:18 UTC, PichuChen commented on internal/repository/article.go
> +//BBSPopularArticleRecord : Mock of bbs.PopularArticleRecord
目前協定中有回傳 money 嗎？ 如果有的話那就先以簡單為原則，先這樣過後面再修好了...

2021-02-23 05:54 UTC, wagaru commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
> @wagaru 哪個 PR 有編號嗎？

#85 這個

> 然後目前作法是切開成三個 Package，理論上應該是比較晚 Merge 的那個要再把他整個串起來

好的

2021-02-23 12:54 UTC, gn01842919 commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
對... 我想我懂你意思了，了解，那這邊就不加 BBS

2021-02-23 12:57 UTC, gn01842919 commented on internal/repository/article.go
> +//BBSPopularArticleRecord : Mock of bbs.PopularArticleRecord
OK

2021-02-23 13:01 UTC, gn01842919 commented on internal/usecase/article_mock_test.go
> +func (repo *MockRepository) GetPopularArticleRecords(ctx context.Context) ([]repository.BBSPopularArticleRecord, error) {
Fixed

2021-02-23 13:02 UTC, gn01842919 commented on internal/repository/article.go
> +type BBSPopularArticleRecord interface {
Fixed

2021-02-24 04:36 UTC, PichuChen commented on internal/repository/board.go
> +	BoardId() string
```suggestion
	BoardID() string
```

2021-02-24 04:37 UTC, PichuChen commented on internal/usecase/board_mock_test.go
> +	// TODO
```suggestion
	// TODO: return some articles with mocking argument?
```

2021-02-24 11:57 UTC, gn01842919 commented on internal/repository/board.go
> +	BoardId() string
Fixed. Sorry for that.

2021-02-24 11:58 UTC, gn01842919 commented on internal/usecase/board_mock_test.go
> +	// TODO
Fixed

2021-02-28 17:39 UTC, PichuChen approved these changes
LGTM

2021-03-02 13:32 UTC, linmeichu commented
LGTM！🥳

2021-03-04 14:53 UTC, linmeichu approved these changes

2021-03-04 20:17 UTC, merged