修正無用函數跟簡化宣告
Ptt-official-app/Ptt-backend pull request #99
Opened 2021-02-23 09:37 UTC by y2468101216

## 👏 解決掉的 issue / Resolved Issues
- close #94

## 📝 相關的 issue / Related Issues
- #90

## ⛏ 變更內容 / Details of Changes
移除無用函數以及簡化宣告

2021-02-23 10:01 UTC, PichuChen requested changes

2021-02-23 10:01 UTC, PichuChen commented on internal/delivery/http/route_classes.go
>  	// // get single board
這邊應該也可以拿掉，不然會滿不知其所以然的

2021-02-24 02:59 UTC, y2468101216 commented on internal/delivery/http/route_classes.go
>  	// // get single board
done

2021-02-24 05:25 UTC, PichuChen commented
LGTM

2021-02-24 05:25 UTC, merged